// src/lib/dicts/en.ts
import { Dictionary } from './types';

export const en: Dictionary = {
  accountDeleted: "Account deactivated. Goodbye!",
  adBuyerMustPassKYC: "Buyer must pass KYC",
  adCash: "Cash",
  adCashMethod: "{cash} / Method",
  adCounterpartyProtection: "Counterparty protection",
  adFinalPrice: "Final price",
  adMinTrades: "Minimum successful trades",
  adOnlyVerified: "Only verified",
  adPaymentTime: "Payment time",
  adTerms: "Trade terms (Description)",
  adTrades: "trades",
  addAddressBtn: "Add address",
  addAddressDesc: "Add an address to make withdrawals faster",
  addressAdded: "Address added",
  addressBookTitle: "Address Book",
  addressDeleted: "Address deleted",
  addressPlaceholder: "Enter wallet address",
  adminActiveDisputes: "Active disputes",
  adminActiveTrades: "Active trades",
  adminAllLevels: "All levels",
  adminAllOps: "All",
  adminAllStatus: "All statuses",
  adminAmount: "Amount",
  adminApprove: "Approve",
  adminApproveBtn: "Approve",
  adminBack: "Back",
  adminBlacklist: "Blacklist",
  adminBuyer: "Buyer",
  adminCancelDeal: "Cancel deal",
  adminCashDesks: "Cash desks",
  adminChatHistory: "Chat history",
  adminCodesActive: "Active",
  adminCodesFees: "Fees (earned)",
  adminCodesOps: "Codes",
  adminCodesTotal: "Total",
  adminCodesUsed: "Used",
  adminCodesVolume: "Volume (used)",
  adminCompleteDeal: "Complete deal",
  adminConfirm: "I have sent",
  adminCredited: "Credited by admin",
  adminCrypto: "Deposit/Withdrawal",
  adminCryptoOps: "Crypto",
  adminDashboard: "Dashboard",
  adminDebited: "Debited by admin",
  adminDisputeArbitration: "Trade Appeal #{id}",
  adminDisputeTitle: "Trade Appeal #{id}",
  adminDisputeSubtitle: "DISPUTE MANAGEMENT",
  adminDisputeOpen: "Dispute open",
  adminDisputeView: "Chat History and Dispute Resolution",
  adminDisputes: "Disputes",
  adminDocPhoto: "Document photo",
  adminExchangeOps: "Exchanges",
  adminExchanges: "Exchanges",
  adminExchangesPending: "Pending",
  adminExchangesTotal: "Total",
  adminFeesToday: "Fees today",
  adminFiat: "Fiat",
  adminForward: "Forward",
  adminFreeze: "Freeze",
  adminGlobalRate: "Global rate",
  adminInQueue: "IN QUEUE",
  adminInvitePartner: "Invite partner",
  adminKYC: "KYC",
  adminKYCCheck: "KYC check",
  adminKYCRequest: "Request #{id}",
  adminKYCVerified: "KYC verified",
  adminLevels: "Levels",
  adminLoading: "Loading...",
  adminNoDisputes: "No active disputes",
  adminNoExchanges: "No exchange requests",
  adminNoOps: "No operations",
  adminNoTransactions: "No transactions",
  adminNoUsers: "No users",
  adminOf: "of",
  adminOperations: "Operations",
  adminPage: "Pg.",
  adminPanel: "Admin Panel (Appeal)",
  adminPartnerDesc: "Through this link, the user will immediately receive the Partner level and a 50 USDT bonus",
  adminPartnerLink: "Partner Link",
  adminPartners: "Partners",
  adminPaymentReceived: "Payment received",
  adminPending: "Pending",
  adminPhotoNotUploaded: "Photo not uploaded",
  adminRateFrozenWarn: "Rate is frozen. Changes unavailable.",
  adminReceiveAmount: "Receives",
  adminReject: "Reject",
  adminRejectBtn: "Reject",
  adminReturn: "Return",
  adminReturnCryptoToSeller: "Returning crypto to seller",
  adminSearch: "Search",
  adminSearchPlaceholder: "Search (username, name, Telegram ID)",
  adminSeller: "Seller",
  adminSendAmount: "Gives",
  adminSendToAddress: "Send to address",
  adminSendToNumber: "Send to number",
  adminStats: "Statistics",
  adminSubtitle: "P2P Management",
  adminTMTBalance: "TMT Balance",
  adminTitle: "Admin Panel",
  adminTotalUsers: "Users",
  adminTransferCryptoToBuyer: "Transferring crypto to buyer",
  adminTxId: "Check TxID",
  adminUSDTBalance: "USDT Balance",
  adminUser: "User",
  adminUserDetails: "User",
  adminUserInfo: "User Information",
  adminUserName: "Name",
  adminUserNickname: "Nickname",
  adminUserRegDate: "Registration date",
  adminUsers: "Users",
  adminVolume: "Trade volumes",
  adminVolume24h: "24h volume",
  adminVolume7d: "7d volume",
  adminWithdrawQueue: "Withdrawal queue",
  all: "All",
  alyCaly: "Exchange",
  amount: "Amount",
  anonymous: "Anonymous",
  apiDesc: "We are working on a powerful API for automating your trade and integrating with external services.",
  apiManagement: "API Management",
  apiTitle: "API Management",
  ashgabat: "Ashgabat",
  asset: "Asset",
  autoReply: "Trade terms (Auto-reply)",
  avatarUploadError: "Avatar upload error",
  bad: "Bad",
  balanceLabel: "Total Balance",
  balkanabat: "Balkanabat",
  becomePro: "Become Pro",
  botAccountUnlinked: "🔗 Account unlinked. Use /start to relink.",
  botAccountVerified: "Your account has been successfully verified 🎉",
  botAdDeactivated: "Your ad has been deactivated.",
  botAdExpired: "⏰ <b>Ad expired</b>",
  botAdPublished: "📢 <b>Ad published!</b>",
  botAdminWillReview: "An administrator will review the dispute shortly.",
  botAmount: "Amount",
  botBackToWallet: "👛 Back to wallet",
  botBuyer: "👤 Buyer",
  botCancelledByUser: "Cancelled by user",
  botCheckTrades: "/status - Check trade status",
  botConnectAccountTip: "🔗 To link your account, use the button in the app.",
  botCreateAd: "➕ Create ad",
  botCreateNewAd: "You can create a new ad at any time.",
  botCryptoAmount: "🪙 Cryptocurrency",
  botDepositReceived: "Deposit credited!",
  botDepositSuccess: "Funds successfully added to your balance.",
  botDisableNotifications: "/disable - Disable notifications",
  botDisabled: "❌ Disabled",
  botDisputeOpened: "⚠️ Dispute opened for trade {orderId}. Wait for the administrator.",
  botEnableNotifications: "/enable - Enable notifications",
  botEnabled: "✅ Enabled",
  botEnglish: "🇬🇧 English",
  botExclusiveDeals: "✅ Participation in exclusive deals",
  botFrom: "👤 From",
  botFromUser: "👤 From",
  botGoToP2P: "📋 Go to P2P",
  botHelpCommand: "/help - Help",
  botHelpCommands: "⚙️ <b>Commands:</b>",
  botHelpDesc1: "🤖 I am a P2P bot for trade notifications.",
  botHelpDesc2: "📱 <b>How it works:</b>\n1. Link your account in the app\n2. Receive trade notifications\n3. Manage settings",
  botHelpTitle: "❓ <b>Help</b>",
  botInitiator: "👤 Initiator",
  botKYCApproved: "✅ <b>KYC approved!</b>",
  botKYCRejected: "❌ <b>KYC rejected</b>",
  botKeepItUp: "Keep it up! 🙌",
  botLanguageSelected: "✅ Language selected: ",
  botMessages: "🔔 Messages from counterparties",
  botMyAds: "📋 My ads",
  botMyCommands: "📋 <b>My commands:</b>",
  botMyOrders: "📋 My orders",
  botMyProfile: "👤 My profile",
  botNetwork: "Network",
  botNewMessage: "💬 <b>New message</b>",
  botNewOrder: "🛒 <b>New trade created!</b>",
  botNewReview: "⭐ <b>New review!</b>",
  botNoActiveDeals: "You have no active trades.",
  botNotificationsCommand: "/notifications - Notification management",
  botNotificationsDisabled: "❌ Notifications disabled!",
  botNotificationsEnabled: "✅ Notifications enabled!",
  botNotificationsStatus: "🔔 <b>Notifications:</b> {status}\n\nUse /enable or /disable to manage.",
  botNowAvailable: "Now available to you:",
  botNowYouWillReceive: "Now you will receive:",
  botOpenApp: "🚀 Open App",
  botOpenChat: "💬 Open Chat",
  botOpenOrder: "📋 Open Order",
  botOpenProfile: "👤 Open Profile",
  botOrderAmount: "💰 Amount",
  botOrderCancelled: "❌ <b>Trade cancelled</b>",
  botOrderCompleted: "🎉 <b>Trade completed!</b>",
  botOrderNotifications: "🔔 New trade notifications",
  botOrderPaid: "✅ <b>Buyer confirmed payment!</b>",
  botP2PAssistant: "I am your personal P2P assistant.",
  botPaymentConfirmed: "✅ Payment confirmed for trade {orderId}!",
  botPaymentStatus: "🔔 Payment and confirmation statuses",
  botPaymentTime: "⏱ Payment time",
  botPendingPayment: "Pending payment",
  botProfile: "Profile",
  botReason: "Reason",
  botReceived: "🪙 Received",
  botRetryKYC: "📤 Retry KYC",
  botRussian: "🇷🇺 Russian",
  botSecurityUpdates: "🔔 Important security updates",
  botSelectLanguage: "🌍 Select language / Выберите язык / Dil saýlaň",
  botSeller: "👤 Seller",
  botStatus: "Status",
  botThankForVerify: "Thanks for verifying!",
  botThankYou: "Thanks for using P2P Market! 🙏",
  botThanksForConnect: "Thanks for connecting to notifications.",
  botTip: "💡 <b>Tip:</b> Enable notifications to not miss important events!",
  botTrustedLevel: "✅ Increased trust level",
  botTryAgain: "You can upload documents again.",
  botTurkmen: "🇹🇲 Türkmençe",
  botUnknownCommand: "❓ Unknown command. Use /help for a list of commands.",
  botUnlimitedAds: "✅ Create ads without limits",
  botUnlinkAccount: "/unlink - Unlink account",
  botWelcome: "👋 <b>Welcome to P2P Market!</b>",
  botWelcomeUser: "👋 <b>Welcome, {username}!</b>",
  botYourActiveDeals: "📊 <b>Your active trades:</b>\n\nClick on a trade to open:",
  botYourAd: "Your ad is now visible in the market!",
  buy: "Buy",
  buyBtn: "Buy",
  cancel: "Cancel",
  cancelBtn: "CANCEL",
  card: "Bank Card",
  cash: "Cash in city",
  chatDispute: "Dispute / Appeal",
  chatNoMessages: "No messages in chat",
  chatPlaceholder: "Type a message...",
  chatProblems: "Having problems?",
  chatRecently: "Was recently",
  chatSelectImage: "Please select an image",
  chatSendError: "Send error",
  city: "City",
  codeActive: "Active",
  codeCancelled: "Cancelled",
  codeCommission: "Commission",
  codeCopyInfo: "Copy the code and give it to the recipient",
  codeCreateBtn: "Create code",
  codeEmptyHistory: "History is empty",
  codeEmptyHistorySub: "You haven't created or activated any codes yet",
  codeEnterPlaceholder: "TM-USDT-500-...",
  codeExpired: "Expired",
  codeExpires: "Expires",
  codeExpiresIn: "Validity: 24 hours",
  codeFee: "Fee",
  codeGenerated: "Code created!",
  codeIdKey: "ID Key",
  codeLabel: "Promo Code",
  codeOneTime: "Can be activated only once",
  codeRedeemBtn: "Activate code",
  codeRedeemSuccess: "Money credited!",
  codeUsed: "Used",
  codeValidUntil: "Expires",
  codeWarning1: "⚠️ Check the code before activating",
  codeWarning2: "⚠️ The code can be used only once",
  codeWarning3: "⚠️ You cannot activate your own code",
  codeYouCreated: "You created",
  codeYouRedeemed: "You activated",
  codesHistory: "History",
  codesSubtitle: "Cash settlements",
  codesTitle: "Promo Codes",
  comingSoon: "Soon",
  completion: "completed",
  confirm: "Confirm",
  confirmCancel: "Are you sure you want to cancel the deal?",
  confirmDeleteAd: "Are you sure you want to delete the ad?",
  confirmRec: "Confirm Receipt",
  copied: "Copied",
  createAd: "Create ad",
  createAdHeader: "Create Ad",
  createAdWarning: "Check all data carefully. Changes after publication are possible in the \"My Ads\" section.",
  createCode: "Create code",
  cryptocurrency: "Cryptocurrency",
  currentLevel: "Your current level",
  cykarmak: "Withdrawal",
  dashoguz: "Dashoguz",
  daysText: "14 Days",
  defaultLabel: "Default",
  deleteAccount: "Delete account",
  deleteAccountBtn: "YES, DELETE",
  deleteAccountConfirmDesc: "This action deactivates your profile and hides all ads. Your transactions will remain in the database for reporting.",
  deleteAccountConfirmTitle: "Are you sure?",
  deleteAddressConfirm: "Are you sure you want to delete this address?",
  digitalDollar: "Digital dollar",
  edit: "Edit",
  email: "Email",
  emptyAddressBook: "Address book is empty",
  enterAddress: "Enter address",
  enterAmount: "Enter amount",
  error: "An error occurred",
  exAvailable: "Available",
  exBonusUsed: "Debited from bonuses",
  exCancelled: "Cancelled",
  exCommission: "Commission",
  exConnectionError: "Connection error",
  exEnterPhone: "Enter your phone number",
  exFeeNote: "* Fee is debited first from the bonus account, then from the main USDT balance.",
  exFeePercent: "Fee (%)",
  exHistory: "Exchange history",
  exInstruction: "Transfer {amount} TMT to the number {phone} and wait for administrator confirmation.",
  exInsufficientBalanceFee: "Insufficient balance to pay the fee",
  exInsufficientUsdt: "Insufficient USDT for exchange and fee",
  exMainUsed: "Debited from main",
  exMinAmount: "Min. amount",
  exNetworkFee: "Network fee will be deducted from the transfer amount.",
  exPending: "Pending",
  exPhonePlaceholder: "+993 6X XX-XX-XX",
  exRate: "Rate",
  exReverse: "Switch direction",
  exSendTMT: "Transfer {amount} TMT",
  exSendToAdmin: "Transfer TMT to administrator's number",
  exSettings: "Exchange settings",
  exSuccess: "Success",
  exTMTName: "Turkmen Manat",
  exTitle: "Exchange",
  exUSDTName: "Tether USDT",
  exWhereToSend: "Where to send Manats?",
  exYouGive: "You give",
  exYouPay: "You pay",
  excellent: "Excellent",
  exchangePrice: "Exchange",
  exchangeStub: "This section is temporarily unavailable for legal reasons.",
  faqAMLTitle: "AML Checks",
  faqAPITitle: "API Keys",
  faqArbitration: "What is an appeal?",
  faqArbitrationDesc: "Dispute resolution by a platform admin in case of trade issues.",
  faqContactTelegram: "Contact on Telegram",
  faqHowCreateAPI: "How to create an API key?",
  faqHowCreateAPIDesc: "API section is in development and will be available soon.",
  faqHowDepositCash: "How to deposit cash?",
  faqHowDepositCashDesc: "Go to Wallet -> Deposit -> Cash and select your city.",
  faqHowDepositCrypto: "How to deposit crypto?",
  faqHowDepositCryptoDesc: "Go to Wallet -> Deposit -> Crypto and follow the instructions.",
  faqHowInvite: "How to invite a friend?",
  faqHowInviteDesc: "Copy your link in Profile -> Referral Program.",
  faqHowLevelUp: "How to level up?",
  faqHowLevelUpDesc: "Increase trade volume and pass verification.",
  faqHowWithdrawTime: "Withdrawal time?",
  faqHowWithdrawTimeDesc: "Withdrawal to crypto wallets takes up to 15 minutes, cash — by agreement with the operator.",
  faqLegalDocs: "Legal Documents",
  faqLevelsTitle: "Financial Levels",
  faqNetSupport: "Which networks are supported?",
  faqNetSupportDesc: "We support USDT on TRC-20, ERC-20, BEP-20 and Aptos networks.",
  faqNoResults: "Nothing found",
  faqOfficesTitle: "Offices",
  faqP2PDetails: "How does P2P work?",
  faqP2PDetailsDesc: "You select an ad, transfer money to a partner, and the platform guarantees receipt of crypto.",
  faqP2PTimeout: "What if the partner doesn't pay?",
  faqP2PTimeoutDesc: "The trade will be automatically cancelled after the time expires.",
  faqQuestionsLeft: "Any questions left?",
  faqReferralTitle: "Referral Program",
  faqRewards: "What rewards?",
  faqRewardsDesc: "You receive 15 USDT for each friend who makes their first trade.",
  faqRiskScore: "What is Risk Score?",
  faqRiskScoreDesc: "This is a risk indicator for your wallet. High risk can lead to blocking.",
  faqSearchPlaceholder: "Search questions...",
  faqSectionAML: "AML Checks",
  faqSectionAPI: "API Keys",
  faqSectionAccount: "Account and Security",
  faqSectionFinance: "Deposit and Withdrawal",
  faqSectionLevels: "Financial Levels",
  faqSectionOffices: "Offices",
  faqSectionP2P: "P2P Platform",
  faqSectionReferral: "Referral Program",
  faqSubtitle: "FAQ & Documentation",
  faqSupportNote: "Our support specialists work 24/7 and are ready to help you at any time.",
  faqTitle: "Support Center",
  faqTryChangingQuery: "Try changing your query",
  faqWhatIsAML: "What is AML?",
  faqWhatIsAMLDesc: "Anti-money laundering system checking the purity of your transactions.",
  faqWhereOffices: "Where are the offices?",
  faqWhereOfficesDesc: "Our offices are located in all velayats of Turkmenistan.",
  faqWithdrawTime: "How fast does money arrive?",
  faqWithdrawTimeDesc: "Usually withdrawal takes from 5 to 15 minutes.",
  fastConfirm: "Fast confirmation",
  fiat: "Fiat",
  fiatCurrency: "Fiat currency",
  filterAmount: "Amount",
  fixed: "Fixed",
  floating: "Floating",
  goBack: "Go back",
  help: "Help",
  helpSubtitle: "Information and support",
  iPay: "I paid",
  insufficientUsdtSeller: "Insufficient USDT on seller's balance",
  insufficientTmtSeller: "Insufficient TMT on seller's balance",
  kycApproved: "Account confirmed",
  kycApprovedDesc: "All limits and trade with verified merchants are available to you.",
  kycLabel: "Verification",
  kycMaxFileSize: "File size must be less than 5MB",
  kycNextStepDone: "After approval, you will receive a verification mark",
  kycNextSteps: "What next?",
  kycOnCheck: "On check",
  kycOnlyJpegPng: "Only JPEG and PNG images",
  kycOpenCam: "Open Camera / Gallery",
  kycOpenCamera: "Open Camera / Gallery",
  kycOr: "or",
  kycPass: "Pass",
  kycPending: "On check",
  kycPendingDesc: "The administrator is checking your documents. This usually takes 10-15 minutes.",
  kycPendingDesc2: "The administrator is checking your documents. This usually takes 10-15 minutes.",
  kycPendingTitle: "Application on check",
  kycPendingTitle2: "Application on check",
  kycPhotoRequired: "Please upload both photos first",
  kycPossibleReasons: "Possible reasons:",
  kycPossibleReasons2: "Possible reasons:",
  kycReason1: "Photo is blurry or not all data is visible",
  kycReason2: "Document has expired",
  kycReason3: "Photo doesn't match your profile",
  kycReasonBlurry: "Photo is blurry or not all data is visible",
  kycReasonExpired: "Document has expired",
  kycReasonMismatch: "Photo doesn't match your profile",
  kycRejected: "Rejected",
  kycRejectedDesc: "The administrator couldn't confirm your data.",
  kycRejectedDesc2: "The administrator couldn't confirm your data.",
  kycRejectedTitle: "Application rejected",
  kycRejectedTitle2: "Application rejected",
  kycRequired: "KYC verification required",
  kycSecurity: "Platform security",
  kycSelectFile: "Select file",
  kycStep1: "Step 1: Upload document photo",
  kycStep1Title: "Step 1: Selfie with passport",
  kycStep1Wait: "Wait for verification within 15 minutes.",
  kycStep2: "Step 2: Passport scan",
  kycStep2Check: "Check status in the Profile section.",
  kycStep2Title: "Step 2: Passport scan",
  kycStep3Title: "Step 3: Submit for check",
  kycSelfieWithPassport: "Selfie with passport",
  kycPassportScan: "Passport scan",
  kycStep3Trade: "After confirmation, all features will be available to you.",
  kycSubmitBtn: "Submit for check",
  kycSubmitError: "Error submitting application",
  kycSubmitSuccess: "Application submitted! Wait for administrator review.",
  kycSubmitting: "Submitting...",
  kycTitle: "Verification (KYC)",
  kycVerifiedDesc: "All limits and trade with verified merchants are available to you.",
  kycVerifiedTitle: "Account confirmed",
  kycWhatNext: "What next?",
  kycWhy: "Why is KYC needed?",
  kycWhyDesc: "KYC helps protect the platform from fraud and ensures the security of your funds.",
  kycWhyDesc2: "KYC helps protect the platform from fraud and ensures the security of your funds.",
  kycWhyTitle: "Why is KYC needed?",
  labelPlaceholder: "For example: My Ledger",
  labelTitle: "Name (optional)",
  lastReviews: "Last reviews",
  limit: "Limit",
  limitsError: "Specify limits",
  linkCopied: "Link copied",
  loading: "Loading...",
  loadingAddresses: "Loading addresses...",
  localCurrency: "Local currency",
  mary: "Mary",
  maxLimit: "Max. limit",
  meetingCity: "Meeting city",
  merchantCenter: "P2P Center",
  min: "min.",
  minLimit: "Min. limit",
  minTrades: "Min. trades",
  minTradesRequired: "Minimum trades: {min} (You have: {current})",
  mpCompletion: "Completed",
  mpLimit: "Limit",
  mpOnPlatform: "On platform since",
  mpPositiveReviews: "positive reviews",
  mpSellerAds: "Seller ads",
  mpTrades: "Trades",
  mpVolume: "Volume",
  myAds: "My Ads",
  myOrders: "My Orders",
  navAlys: "Exchange",
  navGapjyk: "Wallet",
  navP2P: "P2P Market",
  networkError: "Network error",
  networkLabel: "Network",
  neutral: "Neutral",
  newAddressTitle: "New Address",
  nickname: "Nickname",
  noAds: "No active ads for",
  noAdsDesc: "Try changing the amount or currency ({asset}/{fiat})",
  noComment: "No comment",
  noLabel: "No label",
  noOrders: "You have no trades yet",
  notifications: "Notifications",
  notificationsDisabled: "Notifications disabled",
  notificationsEnabled: "Notifications enabled",
  onPayout: "On payouts",
  onReceive: "On receive",
  online: "Online",
  onlyWithKyc: "Only with KYC",
  openOrderBtn: "Open Order",
  orderAttachCheck: "Attach payment receipt",
  orderAttachPhoto: "Please attach a photo or screenshot of payment",
  orderCard: "💳 Bank Card",
  orderCash: "🤝 Cash",
  orderClickToChange: "Click to change",
  orderCreated: "Order successfully created!",
  orderCredited: "credited to wallet",
  orderDebited: "debited from wallet",
  orderDetailsInChat: "Details in chat",
  orderDisputeConfirm: "Are you sure you want to call an appeal? The trade will be frozen until the dispute is resolved.",
  orderDisputeError: "Error sending appeal",
  orderDisputeSent: "Appeal sent! Admin will be notified.",
  orderExpiredMsg: "Trade expired. Payment is not possible.",
  orderFrozen: "⚠️ Trade frozen. Wait for the appeal decision.",
  orderId: "Order",
  orderPaidMsg: "📢 I paid for the order. Attaching the receipt.",
  orderPaidSellerMessage: "{seller}, please:\n1️⃣ Check receipt of funds\n2️⃣ Confirm the trade in the app",
  orderReviewError: "Error sending review",
  orderReviewPlaceholder: "Write a few words about the trade (optional)...",
  orderSystemDisputeMsg: "🚨 Trade suspended. Wait for administrator resolution.",
  orderTmcell: "📱 Tmcell",
  orderUpdateError: "Error updating status",
  orderUploadCheck: "Upload Receipt",
  p2pCash: "Cash",
  p2pLimit: "Limit",
  p2pMerchant: "Merchant",
  p2pMethod: "P2P Method",
  p2pMinTrades: "Minimum trades",
  p2pNoAds: "No active ads for",
  p2pPayAmount: "Payment amount",
  p2pReceiveAmount: "You receive",
  p2pTradeConditions: "Trade conditions",
  p2pVerifyCode: "KYC required (Verification)",
  payAmount: "Payment amount",
  paymentMethodError: "Select payment method",
  paymentMethods: "Payment methods",
  paymentWindow: "Payment window",
  perUnit: "per unit",
  percentFromMarket: "Percent from market (%)",
  phone: "Phone",
  positiveReviews: "positive reviews",
  price: "Price",
  priceOrPercentError: "Specify price or percent",
  pricePerUnit: "Price per 1 unit",
  priceType: "Price type",
  private: "Private",
  proProgress: "Progress to Pro",
  proRequestError: "Error submitting application",
  proRequestSent: "Application sent to support",
  processing: "Processing...",
  profileTitle: "Profile",
  profileUSDTVolume: "USDT Volume",
  profileUpdated: "Profile updated",
  protectionSettings: "Protection settings",
  public: "Public",
  publish: "Publish",
  publishAd: "Publish Ad",
  rating: "Rating (%)",
  ratingText: "Rating 4.8+",
  receiveAmount: "You receive",
  redeemCode: "Activate",
  refBonusDesc: "Bonus is credited after your friend makes their first trade.",
  refBonusPerFriend: "+15 USDT for each friend",
  refInviteFriends: "Invite friends to start earning together with RapTM",
  refRules: "Program Rules",
  refRulesDesc: "Invite friends and receive a bonus in USDT for each of their trades on the platform. Bonuses are credited instantly.",
  refRulesTitle: "Program Rules",
  referralActive: "Active",
  referralCopy: "Copy",
  referralEarned: "Earned",
  referralHistory: "Referral history",
  referralLink: "Your link",
  referralNoData: "You have no referrals yet",
  referralRewardReceived: "🎁 You received +15 USDT for an active referral!",
  referralShare: "Invite",
  referralStats: "Statistics",
  referralStatusActive: "Active",
  referralStatusPending: "Waiting for trade",
  referralSubtitle: "Invite friends and earn",
  referralTitle: "Referral Program",
  referralTotal: "Total invited",
  refresh: "Refresh",
  requestError: "Request error",
  returnToWallet: "Return to wallet",
  reviewSuccess: "Review saved. Thanks!",
  reviewTitle: "Rate the trade",
  safeDeal: "Safe deal",
  salmak: "Deposit",
  save: "Save",
  saveAddressBtn: "Save address",
  searchPlaceholder: "Search by amount...",
  sec2faDesc: "Google Authenticator protection",
  sec2faDisable: "Disable 2FA",
  sec2faDisableInput: "Enter code from the app to disable",
  sec2faDisableWarning: "Disabling 2FA reduces your account security.",
  sec2faEnable: "Setup 2FA",
  sec2faEnableScan: "Scan the QR code in the app",
  sec2faEnableSuccess: "After enabling 2FA, it will be requested for every withdrawal.",
  sec2faInput6Digit: "Enter 6-digit code",
  sec2faManual: "Or enter secret key manually:",
  sec2faNotSet: "Not set",
  sec2faSetupError: "2FA setup error",
  secChangePin: "Change PIN code",
  secConfirm: "Confirm",
  secConfirmPin: "Confirm PIN code",
  secEmailAddress: "Email address",
  secEmailDesc: "Notifications about important events will be sent to this address.",
  secEmailLinkDesc: "Link email",
  secEnter6Digit: "Enter 6-digit code",
  secFullProtection: "Your account is fully protected",
  secInvalidCode: "Invalid code",
  secLinkEmail: "Email Linking",
  secLinkPhone: "Phone Linking",
  secLowProtection: "Increase account security",
  secNewPin: "New PIN code",
  secPhoneLinkDesc: "Link phone number",
  secPhoneNumber: "Phone number",
  secPhoneWarning: "Use a number you have constant access to.",
  secPinDesc: "PIN code for operations",
  secProtectionLevel: "Protection level",
  secSaveEmail: "Save Email",
  secSaveError: "Save error",
  secSavePhone: "Save Number",
  secSavePin: "Save PIN",
  secWarning: "Never share your password, PIN code, or 2FA secret with anyone. RapTM employees will never ask for this data.",
  security: "Security",
  securityPin: "Security & PIN",
  securityWarning: "Warning! Never release crypto before receiving cash.",
  seeAllReviews: "See all",
  selectImage: "Please select an image",
  sell: "Sell",
  sellBtn: "Sell",
  serverError: "Server error",
  setAsDefault: "Set as default",
  shareProfile: "Share profile",
  stats: "Statistics",
  statusCancelled: "Cancelled",
  statusCompleted: "Completed",
  statusLabel: "Status",
  statusPaid: "Paid",
  statusPending: "Pending payment",
  step1: "Message partner in chat for meeting.",
  step2: "After transferring money, click the 'I paid' button.",
  step3: "Partner will confirm receipt and coins will be credited.",
  success: "Success!",
  time: "min",
  tmcell: "Tmcell (Phone number)",
  totalCost: "Total cost",
  tradeConditions: "Trade conditions",
  tradeConditionsPlaceholder: "Write details (e.g.: only to Halkbank card)",
  trades: "trades",
  turkmenabat: "Turkmenabat",
  typeLabel: "Type",
  unverified: "Unverified",
  updateError: "Update error",
  userLabel: "User",
  verified: "Verified",
  youGive: "You give",
  youReceive: "You receive",
  wal2faRequiredLevel: "For your access level (Pro/Partner), 2FA is mandatory for withdrawals.",
  walActivationCode: "Activation code",
  walAddrError: "Error getting address",
  walAmountRapCode: "Voucher amount",
  walAmountUsdt: "USDT amount",
  walAshgabat: "Ashgabat",
  walAvailableForExchange: "Available for exchange",
  walBalanceUpdated: "Balance updated",
  walBalkanabat: "Balkanabat",
  walBonusAccount: "Bonus account",
  walCash: "Cash",
  walCashOperatorNote: "Our operator will contact you on Telegram to confirm the meeting place in {city}.",
  walCashWithdrawal: "Cash withdrawal",
  walCashWithdrawalNote: "Operator will contact you to organize a meeting.",
  walClaimError: "Error getting USDT",
  walClaimSuccess: "🎉 1000 USDT credited to your account!",
  walCopied: "Copied",
  walCrypto: "Crypto",
  walDashoguz: "Dashoguz",
  walDeposit: "Deposit",
  walDepositAddr: "Deposit address",
  walDepositWithdraw: "Deposit and Withdrawal",
  walEnterAmount: "Enter amount",
  walEnterNetworkAddr: "Enter {network} address",
  walEnterTxId: "Enter or paste TxID",
  walFilterAll: "ALL",
  walFilterDeposit: "DEPOSITS",
  walFilterExchange: "EXCHANGE",
  walFilterWithdraw: "WITHDRAWALS",
  walFullHistory: "Full History",
  walGetTestUsdt: "Get 1000 USDT",
  walGetTestTmt: "Get 1000 TMT",
  walClaimTmtSuccess: "🎉 1000 TMT credited to your account!",
  walTmtDeposit: "TMT Deposit",
  walTmtWithdraw: "TMT Withdrawal",
  walTmtPhone: "Phone number",
  walTmtPhonePlaceholder: "+993 6X XX-XX-XX",
  walTmtDepositNote: "Transfer TMT to administrator's number and enter sender's number.",
  walHistory: "History",
  walInDev: "Feature in development",
  walInsuffBalance: "Insufficient balance",
  walInvalidAddr: "Invalid {network} address",
  walInvalidFormat: "Invalid format",
  walKycRequired: "Please pass KYC verification to withdraw funds",
  walMary: "Mary",
  walMinDeposit: "Minimum deposit {amount} USDT",
  walNetworkError: "Network error",
  walNetworkFeeLabel: "Network fee:",
  walNoOps: "No operations",
  walRapCode: "RapCode",
  walRapCodeActivationNote: "Activation of gift vouchers and internal transfers instantly and with no fee.",
  walRecipientAddr: "Recipient address",
  walRequestCreated: "Request created",
  walScanToPay: "Scan to pay",
  walSearchPlaceholder: "Search by amount, date or TxID...",
  walSeeAll: "See all ({count})",
  walSelectCityWithdraw: "Select city to receive cash",
  walSelectPaymentMethod: "Select payment method",
  walStatusCancelled: "Cancelled",
  walStatusCompleted: "Completed",
  walStatusFailed: "Failed",
  walStatusPending: "Pending",
  walStatusProcessing: "Processing",
  walSubmitRequest: "SUBMIT REQUEST",
  walToReceive: "To receive:",
  walTurkmenabat: "Turkmenabat",
  walTxHash: "Transaction hash (TxID)",
  walUserNotAuth: "User not authorized",
  walValidFormat: "Valid format",
  walVoucherCreation: "Voucher creation",
  walVoucherCreationNote: "Voucher can be given to another user for instant crediting.",
  walWithdrawAll: "WITHDRAW ALL",
  walWithdrawAmount: "Withdrawal amount",
  walWithdrawBtn: "Withdraw funds",
  walWithdrawal: "Withdrawal",
  walWithdrawalNote: "Funds will be credited within 15 minutes",
  walYourCity: "Your city",
  walyutalar: "Currencies",
  whatToDo: "What to do?"
};
