// src/lib/dicts/ru.ts

import { Dictionary } from './types';

export const ru: Dictionary = {
  accountDeleted: "Аккаунт деактивирован. Прощайте!",
  adBuyerMustPassKYC: "Покупатель должен пройти KYC",
  adCash: "Наличные",
  adCashMethod: "{cash} / Метод",
  adCounterpartyProtection: "Защита контрагента",
  adFinalPrice: "Итоговая цена",
  adMinTrades: "Минимум успешных сделок",
  adOnlyVerified: "Только верифицированные",
  adPaymentTime: "Время на оплату",
  adTerms: "Условия сделки (Описание)",
  adTrades: "сделок",
  addAddressBtn: "Добавить адрес",
  addAddressDesc: "Добавьте адрес, чтобы совершать выводы быстрее",
  addressAdded: "Адрес добавлен",
  addressBookTitle: "Адресная книга",
  addressDeleted: "Адрес удален",
  addressPlaceholder: "Введите адрес кошелька",
  adminActiveDisputes: "Активные споры",
  adminActiveTrades: "Активные сделки",
  adminAllLevels: "Все уровни",
  adminAllOps: "Все",
  adminAllStatus: "Все статусы",
  adminAmount: "Сумма",
  adminApprove: "Подтвердить",
  adminApproveBtn: "Одобрить",
  adminBack: "Назад",
  adminBlacklist: "ЧС",
  adminBuyer: "Покупатель",
  adminCancelDeal: "Отменить сделку",
  adminCashDesks: "Кассы",
  adminChatHistory: "История чата",
  adminCodesActive: "Активны",
  adminCodesFees: "Комиссии (заработано)",
  adminCodesOps: "Коды",
  adminCodesTotal: "Всего",
  adminCodesUsed: "Использованы",
  adminCodesVolume: "Объем (использовано)",
  adminCompleteDeal: "Завершить сделку",
  adminConfirm: "Я отправил",
  adminCredited: "Зачислено админом",
  adminCrypto: "Ввод/Вывод",
  adminCryptoOps: "Крипто",
  adminDashboard: "Панель",
  adminDebited: "Списано админом",
  adminDisputeArbitration: "Апелляция сделки #{id}",
  adminDisputeTitle: "Апелляция сделки #{id}",
  adminDisputeSubtitle: "УПРАВЛЕНИЕ СПОРОМ",
  adminDisputeOpen: "Спор открыт",
  adminDisputeView: "Просмотр чата и решение спора",
  adminDisputes: "Споры",
  adminDocPhoto: "Фото документа",
  adminExchangeOps: "Обмены",
  adminExchanges: "Обмены",
  adminExchangesPending: "В ожидании",
  adminExchangesTotal: "Всего",
  adminFeesToday: "Комиссии сегодня",
  adminFiat: "Фиат",
  adminForward: "Вперед",
  adminFreeze: "Заморозить",
  adminGlobalRate: "Глобальный курс",
  adminInQueue: "В ОЧЕРЕДИ",
  adminInvitePartner: "Пригласить партнера",
  adminKYC: "KYC",
  adminKYCCheck: "Проверка KYC",
  adminKYCRequest: "Заявка #{id}",
  adminKYCVerified: "KYC верифицировано",
  adminLevels: "Уровни",
  adminLoading: "Загрузка...",
  adminNoDisputes: "Нет активных споров",
  adminNoExchanges: "Нет заявок на обмен",
  adminNoOps: "Нет операций",
  adminNoTransactions: "Нет транзакций",
  adminNoUsers: "Нет пользователей",
  adminOf: "из",
  adminOperations: "Операции",
  adminPage: "Стр.",
  adminPanel: "Админ-Панель (Апелляция)",
  adminPartnerDesc: "По этой ссылке пользователь сразу получит уровень Partner и бонус 50 USDT",
  adminPartnerLink: "Партнерская ссылка",
  adminPartners: "Партнеры",
  adminPaymentReceived: "Поступила оплата",
  adminPending: "В ожидании",
  adminPhotoNotUploaded: "Фото не загружено",
  adminRateFrozenWarn: "Курс заморожен. Изменения недоступны.",
  adminReceiveAmount: "Получает",
  adminReject: "Отклонить",
  adminRejectBtn: "Отклонить",
  adminReturn: "Возврат",
  adminReturnCryptoToSeller: "Возвращаем крипту продавцу",
  adminSearch: "Найти",
  adminSearchPlaceholder: "Поиск (username, имя, Telegram ID)",
  adminSeller: "Продавец",
  adminSendAmount: "Отдает",
  adminSendToAddress: "Отправить на адрес",
  adminSendToNumber: "Отправить на номер",
  adminStats: "Статистика",
  adminSubtitle: "P2P Management",
  adminTMTBalance: "TMT Баланс",
  adminTitle: "Панель Администратора",
  adminTotalUsers: "Пользователей",
  adminTransferCryptoToBuyer: "Переводим крипту покупателю",
  adminTxId: "Проверьте TxID",
  adminUSDTBalance: "USDT Баланс",
  adminUser: "Пользователь",
  adminUserDetails: "Пользователь",
  adminUserInfo: "Информация о пользователе",
  adminUserName: "Имя",
  adminUserNickname: "Никнейм",
  adminUserRegDate: "Дата регистрации",
  adminUsers: "Пользователи",
  adminVolume: "Объемы торгов",
  adminVolume24h: "Объем 24ч",
  adminVolume7d: "Объем 7д",
  adminWithdrawQueue: "Очередь вывода",
  all: "Все",
  alyCaly: "Обменять",
  amount: "Сумма",
  anonymous: "Аноним",
  apiDesc: "Мы работаем над мощным API для автоматизации вашей торговли и интеграции с внешними сервисами.",
  apiManagement: "API Управление",
  apiTitle: "API Управление",
  ashgabat: "Ашхабад",
  asset: "Актив",
  autoReply: "Условия сделки (Автоответ)",
  avatarUploadError: "Ошибка загрузки аватара",
  bad: "Плохо",
  balanceLabel: "Общий баланс",
  balkanabat: "Балканабад",
  becomePro: "Стать Pro",
  botAccountUnlinked: "🔗 Аккаунт отвязан. Используйте /start для повторной привязки.",
  botAccountVerified: "Ваш аккаунт успешно верифицирован 🎉",
  botAdDeactivated: "Ваше объявление было деактивировано.",
  botAdExpired: "⏰ <b>Объявление истекло</b>",
  botAdPublished: "📢 <b>Объявление опубликовано!</b>",
  botAdminWillReview: "Администратор рассмотрит спор в ближайшее время.",
  botAmount: "Сумма",
  botBackToWallet: "👛 Вернуться в кошелек",
  botBuyer: "👤 Покупатель",
  botCancelledByUser: "Отменена пользователем",
  botCheckTrades: "/status - Проверить статус сделок",
  botConnectAccountTip: "🔗 Чтобы привязать аккаунт, используйте кнопку в приложении.",
  botCreateAd: "➕ Создать объявление",
  botCreateNewAd: "Вы можете создать новое объявление в любое время.",
  botCryptoAmount: "🪙 Криптовалюта",
  botDepositReceived: "Депозит зачислен!",
  botDepositSuccess: "Средства успешно добавлены на ваш баланс.",
  botDisableNotifications: "/disable - Отключить уведомления",
  botDisabled: "❌ Отключены",
  botDisputeOpened: "⚠️ Спор по сделке {orderId} открыт. Ожидайте администратора.",
  botEnableNotifications: "/enable - Включить уведомления",
  botEnabled: "✅ Включены",
  botEnglish: "🇬🇧 English",
  botExclusiveDeals: "✅ Участие в эксклюзивных сделках",
  botFrom: "👤 От",
  botFromUser: "👤 От",
  botGoToP2P: "📋 Перейти в P2P",
  botHelpCommand: "/help - Помощь",
  botHelpCommands: "⚙️ <b>Команды:</b>",
  botHelpDesc1: "🤖 Я P2P бот для уведомлений о сделках.",
  botHelpDesc2: "📱 <b>Как это работает:</b>\n1. Привяжите аккаунт в приложении\n2. Получайте уведомления о сделках\n3. Управляйте настройками",
  botHelpTitle: "❓ <b>Помощь</b>",
  botInitiator: "👤 Инициатор",
  botKYCApproved: "✅ <b>KYC одобрен!</b>",
  botKYCRejected: "❌ <b>KYC отклонён</b>",
  botKeepItUp: "Продолжайте в том же духе! 🙌",
  botLanguageSelected: "✅ Язык выбран: ",
  botMessages: "🔔 Сообщения от контрагентов",
  botMyAds: "📋 Мои объявления",
  botMyCommands: "📋 <b>Мои команды:</b>",
  botMyOrders: "📋 Мои сделки",
  botMyProfile: "👤 Мой профиль",
  botNetwork: "Сеть",
  botNewMessage: "💬 <b>Новое сообщение</b>",
  botNewOrder: "🛒 <b>Новая сделка создана!</b>",
  botNewReview: "⭐ <b>Новый отзыв!</b>",
  botNoActiveDeals: "У вас нет активных сделок.",
  botNotificationsCommand: "/notifications - Управление уведомлениями",
  botNotificationsDisabled: "❌ Уведомления отключены!",
  botNotificationsEnabled: "✅ Уведомления включены!",
  botNotificationsStatus: "🔔 <b>Уведомления:</b> {status}\n\nИспользуйте /enable или /disable для управления.",
  botNowAvailable: "Теперь вам доступны:",
  botNowYouWillReceive: "Теперь вы будете получать:",
  botOpenApp: "🚀 Открыть приложение",
  botOpenChat: "💬 Открыть чат",
  botOpenOrder: "📋 Открыть сделку",
  botOpenProfile: "👤 Открыть профиль",
  botOrderAmount: "💰 Сумма",
  botOrderCancelled: "❌ <b>Сделка отменена</b>",
  botOrderCompleted: "🎉 <b>Сделка завершена!</b>",
  botOrderNotifications: "🔔 Уведомления о новых сделках",
  botOrderPaid: "✅ <b>Покупатель подтвердил оплату!</b>",
  botP2PAssistant: "Я ваш персональный P2P помощник.",
  botPaymentConfirmed: "✅ Оплата по сделке {orderId} подтверждена!",
  botPaymentStatus: "🔔 Статусы оплаты и подтверждения",
  botPaymentTime: "⏱ Время на оплату",
  botPendingPayment: "Ожидание оплаты",
  botProfile: "Профиль",
  botReason: "Причина",
  botReceived: "🪙 Получено",
  botRetryKYC: "📤 Повторить KYC",
  botRussian: "🇷🇺 Русский",
  botSecurityUpdates: "🔔 Важные обновления безопасности",
  botSelectLanguage: "🌍 Выберите язык / Dil saýlaň / Select language",
  botSeller: "👤 Продавец",
  botStatus: "Статус",
  botThankForVerify: "Спасибо за верификацию!",
  botThankYou: "Спасибо за использование P2P Market! 🙏",
  botThanksForConnect: "Спасибо за подключение к уведомлениям.",
  botTip: "💡 <b>Совет:</b> Включите уведомления, чтобы не пропустить важные события!",
  botTrustedLevel: "✅ Повышенный уровень доверия",
  botTryAgain: "Вы можете загрузить документы повторно.",
  botTurkmen: "🇹🇲 Türkmençe",
  botUnknownCommand: "❓ Неизвестная команда. Используйте /help для списка команд.",
  botUnlimitedAds: "✅ Создание объявлений без лимитов",
  botUnlinkAccount: "/unlink - Отвязать аккаунт",
  botWelcome: "👋 <b>Добро пожаловать в P2P Market!</b>",
  botWelcomeUser: "👋 <b>Добро пожаловать, {username}!</b>",
  botYourActiveDeals: "📊 <b>Ваши активные сделки:</b>\n\nНажмите на сделку, чтобы открыть:",
  botYourAd: "Ваше объявление теперь видно в маркете!",
  buy: "Купить",
  buyBtn: "Купить",
  cancel: "Отмена",
  cancelBtn: "ОТМЕНА",
  card: "Банковская карта",
  cash: "Наличные в городе",
  chatDispute: "Спор / Апелляция",
  chatNoMessages: "Сообщений в чате нет",
  chatPlaceholder: "Написать сообщение...",
  chatProblems: "Возникли проблемы?",
  chatRecently: "Был(а) недавно",
  chatSelectImage: "Пожалуйста, выберите изображение",
  chatSendError: "Ошибка отправки",
  city: "Город",
  codeActive: "Активен",
  codeCancelled: "Отменен",
  codeCommission: "Комиссия",
  codeCopyInfo: "Скопируйте и передайте получателю",
  codeCreateBtn: "Создать код",
  codeEmptyHistory: "История пуста",
  codeEmptyHistorySub: "Вы еще не создавали и не активировали коды",
  codeEnterPlaceholder: "TM-USDT-500-...",
  codeExpired: "Истек",
  codeExpires: "Действует до",
  codeExpiresIn: "Срок действия: 24 часа",
  codeFee: "Комиссия",
  codeGenerated: "Код создан!",
  codeIdKey: "ID Ключ",
  codeLabel: "Промокод",
  codeOneTime: "Можно активировать только один раз",
  codeRedeemBtn: "Активировать код",
  codeRedeemSuccess: "Деньги зачислены!",
  codeUsed: "Использован",
  codeValidUntil: "Действует до",
  codeWarning1: "⚠️ Проверьте код перед активацией",
  codeWarning2: "⚠️ Код можно использовать только один раз",
  codeWarning3: "⚠️ Нельзя активировать собственный код",
  codeYouCreated: "Вы создали",
  codeYouRedeemed: "Вы активировали",
  codesHistory: "История",
  codesSubtitle: "Наличные расчеты",
  codesTitle: "Промокоды",
  comingSoon: "Скоро",
  completion: "выполнено",
  confirm: "Подтвердить",
  confirmCancel: "Вы уверены, что хотите отменить сделку?",
  confirmDeleteAd: "Вы уверены, что хотите удалить объявление?",
  confirmRec: "Подтвердить получение",
  copied: "Скопировано",
  createAd: "Создать объявление",
  createAdHeader: "Создать объявление",
  createAdWarning: "Внимательно проверьте все данные. Изменение объявления после публикации возможно в разделе \"Мои объявления\".",
  createCode: "Создать код",
  cryptocurrency: "Криптовалюта",
  currentLevel: "Ваш текущий уровень",
  cykarmak: "Вывод",
  dashoguz: "Дашогуз",
  daysText: "14 Дней",
  defaultLabel: "По умолчанию",
  deleteAccount: "Удалить аккаунт",
  deleteAccountBtn: "ДА, УДАЛИТЬ",
  deleteAccountConfirmDesc: "Это действие деактивирует ваш профиль и скроет все объявления. Ваши транзакции останутся в базе для отчетности.",
  deleteAccountConfirmTitle: "Вы уверены?",
  deleteAddressConfirm: "Вы уверены, что хотите удалить этот адрес?",
  digitalDollar: "Цифровой доллар",
  edit: "Изменить",
  email: "Почта",
  emptyAddressBook: "Книга адресов пуста",
  enterAddress: "Введите адрес",
  enterAmount: "Введите сумму",
  error: "Произошла ошибка",
  exAvailable: "Доступно",
  exBonusUsed: "Списано с бонусов",
  exCancelled: "Отменено",
  exCommission: "Комиссия",
  exConnectionError: "Ошибка соединения",
  exEnterPhone: "Введите номер телефона",
  exFeeNote: "* Комиссия списывается сначала с бонусного счета, затем с основного баланса USDT.",
  exFeePercent: "Комиссия (%)",
  exHistory: "История обменов",
  exInstruction: "Переведите {amount} TMT на номер {phone} и дождитесь подтверждения от администратора.",
  exInsufficientBalanceFee: "Недостаточно баланса для оплаты комиссии",
  exInsufficientUsdt: "Недостаточно USDT для обмена и комиссии",
  exMainUsed: "Списано с основного",
  exMinAmount: "Мин. сумма",
  exNetworkFee: "Комиссия сети будет вычтена из суммы перевода.",
  exPending: "Ожидание",
  exPhonePlaceholder: "+993 6X XX-XX-XX",
  exRate: "Курс",
  exReverse: "Сменить направление",
  exSendTMT: "Переведите {amount} TMT",
  exSendToAdmin: "Переведите TMT на номер администратора",
  exSettings: "Настройки обмена",
  exSuccess: "Успешно",
  exTMTName: "Туркменский Манат",
  exTitle: "Обмен",
  exUSDTName: "Tether USDT",
  exWhereToSend: "Куда отправить Манаты?",
  exYouGive: "Вы отдаете",
  exYouPay: "Вы платите",
  excellent: "Отлично",
  exchangePrice: "Биржа",
  exchangeStub: "Этот раздел временно недоступен по юридическим причинам.",
  faqAMLTitle: "AML Проверки",
  faqAPITitle: "API-ключи",
  faqArbitration: "Что такое апелляция?",
  faqArbitrationDesc: "Это решение спора администратором платформы в случае возникновения проблем в сделке.",
  faqContactTelegram: "Связаться в Telegram",
  faqHowCreateAPI: "Как создать API ключ?",
  faqHowCreateAPIDesc: "Раздел API находится в разработке и будет доступен в ближайшее время.",
  faqHowDepositCash: "Как пополнить наличными?",
  faqHowDepositCashDesc: "Зайдите в Кошелек -> Пополнить -> Наличные и выберите ваш город.",
  faqHowDepositCrypto: "Как пополнить криптой?",
  faqHowDepositCryptoDesc: "Зайдите в Кошелек -> Пополнить -> Крипто и следуйте инструкциям.",
  faqHowInvite: "Как пригласить друга?",
  faqHowInviteDesc: "Скопируйте вашу ссылку в разделе Профиль -> Реферальная программа.",
  faqHowLevelUp: "Как повысить уровень?",
  faqHowLevelUpDesc: "Увеличивайте объем торгов и проходите верификацию.",
  faqHowWithdrawTime: "Время вывода?",
  faqHowWithdrawTimeDesc: "Вывод на крипто-кошельки занимает до 15 минут, наличными — по договоренности с оператором.",
  faqLegalDocs: "Юридические документы",
  faqLevelsTitle: "Финансовые уровни",
  faqNetSupport: "Какие сети поддерживаются?",
  faqNetSupportDesc: "Мы поддерживаем USDT в сетях TRC-20, ERC-20, BEP-20 и Aptos.",
  faqNoResults: "Ничего не найдено",
  faqOfficesTitle: "Офисы",
  faqP2PDetails: "Как работает P2P?",
  faqP2PDetailsDesc: "Вы выбираете объявление, переводите деньги партнеру, а платформа гарантирует получение крипты.",
  faqP2PTimeout: "Что если партнер не платит?",
  faqP2PTimeoutDesc: "Сделка будет автоматически отменена по истечении времени.",
  faqQuestionsLeft: "Остались вопросы?",
  faqReferralTitle: "Реферальная программа",
  faqRewards: "Какие награды?",
  faqRewardsDesc: "Вы получаете 15 USDT за каждого друга, совершившего первую сделку.",
  faqRiskScore: "Что такое Risk Score?",
  faqRiskScoreDesc: "Это показатель риска вашего кошелька. Высокий риск может привести к блокировке.",
  faqSearchPlaceholder: "Поиск по вопросам...",
  faqSectionAML: "AML Проверки",
  faqSectionAPI: "API-ключи",
  faqSectionAccount: "Учетная запись и безопасность",
  faqSectionFinance: "Пополнение и вывод",
  faqSectionLevels: "Финансовые уровни",
  faqSectionOffices: "Офисы",
  faqSectionP2P: "P2P Платформа",
  faqSectionReferral: "Реферальная программа",
  faqSubtitle: "FAQ & Документация",
  faqSupportNote: "Наши специалисты службы поддержки работают 24/7 и готовы помочь вам в любое время.",
  faqTitle: "Центр поддержки",
  faqTryChangingQuery: "Попробуйте изменить запрос",
  faqWhatIsAML: "Что такое AML?",
  faqWhatIsAMLDesc: "Система борьбы с отмыванием денег, проверяющая чистоту ваших транзакций.",
  faqWhereOffices: "Где находятся офисы?",
  faqWhereOfficesDesc: "Наши офисы находятся во всех велаятах Туркменистана.",
  faqWithdrawTime: "Как быстро приходят деньги?",
  faqWithdrawTimeDesc: "Обычно вывод занимает от 5 до 15 минут.",
  fastConfirm: "Быстрое подтверждение",
  fiat: "Фиат",
  fiatCurrency: "Фиатная валюта",
  filterAmount: "Сумма",
  fixed: "Фиксированная",
  floating: "Плавающая",
  goBack: "Вернуться назад",
  help: "Помощь",
  helpSubtitle: "Информация и поддержка",
  iPay: "Я оплатил",
  insufficientUsdtSeller: "Недостаточно USDT на балансе продавца",
  insufficientTmtSeller: "Недостаточно TMT на балансе продавца",
  kycApproved: "Аккаунт подтвержден",
  kycApprovedDesc: "Вам доступны все лимиты и торговля с проверенными мерчантами.",
  kycLabel: "Верификация",
  kycMaxFileSize: "Размер файла должен быть меньше 5MB",
  kycNextStepDone: "После одобрения вы получите галочку верификации",
  kycNextSteps: "Что дальше?",
  kycOnCheck: "На проверке",
  kycOnlyJpegPng: "Только JPEG и PNG изображения",
  kycOpenCam: "Открыть камеру / Галерею",
  kycOpenCamera: "Открыть камеру / Галерею",
  kycOr: "или",
  kycPass: "Пройти",
  kycPending: "На проверке",
  kycPendingDesc: "Администратор проверяет ваши документы. Обычно это занимает 10-15 минут.",
  kycPendingDesc2: "Администратор проверяет ваши документы. Обычно это занимает 10-15 минут.",
  kycPendingTitle: "Заявка на проверке",
  kycPendingTitle2: "Заявка на проверке",
  kycPhotoRequired: "Сначала загрузите оба фото",
  kycPossibleReasons: "Возможные причины:",
  kycPossibleReasons2: "Возможные причины:",
  kycReason1: "Фото нечеткое или не видно всех данных",
  kycReason2: "Документ просрочен",
  kycReason3: "Фото не соответствует вашему профилю",
  kycReasonBlurry: "Фото нечеткое или не видно всех данных",
  kycReasonExpired: "Документ просрочен",
  kycReasonMismatch: "Фото не соответствует вашему профилю",
  kycRejected: "Отклонено",
  kycRejectedDesc: "Администратор не смог подтвердить ваши данные.",
  kycRejectedDesc2: "Администратор не смог подтвердить ваши данные.",
  kycRejectedTitle: "Заявка отклонена",
  kycRejectedTitle2: "Заявка отклонена",
  kycRequired: "Требуется верификация (KYC)",
  kycSecurity: "Безопасность платформы",
  kycSelectFile: "Выбрать файл",
  kycStep1: "Шаг 1: Загрузите фото документа",
  kycStep1Title: "Шаг 1: Селфи с паспортом",
  kycStep1Wait: "Ожидайте проверки в течение 15 минут.",
  kycStep2: "Шаг 2: Скан паспорта",
  kycStep2Check: "Проверьте статус в разделе Профиль.",
  kycStep2Title: "Шаг 2: Скан паспорта",
  kycStep3Title: "Шаг 3: Отправьте на проверку",
  kycSelfieWithPassport: "Селфи с паспортом",
  kycPassportScan: "Скан паспорта",
  kycStep3Trade: "После подтверждения вам будут доступны все функции.",
  kycSubmitBtn: "Отправить на проверку",
  kycSubmitError: "Ошибка при отправке заявки",
  kycSubmitSuccess: "Заявка отправлена! Ожидайте проверки администратором.",
  kycSubmitting: "Отправка...",
  kycTitle: "Верификация (KYC)",
  kycVerifiedDesc: "Вам доступны все лимиты и торговля с проверенными мерчантами.",
  kycVerifiedTitle: "Аккаунт подтвержден",
  kycWhatNext: "Что дальше?",
  kycWhy: "Зачем нужен KYC?",
  kycWhyDesc: "KYC помогает защитить платформу от мошенничества и обеспечивает безопасность ваших средств.",
  kycWhyDesc2: "KYC помогает защитить платформу от мошенничества и обеспечивает безопасность ваших средств.",
  kycWhyTitle: "Зачем нужен KYC?",
  labelPlaceholder: "Например: Мой Ledger",
  labelTitle: "Название (необязательно)",
  lastReviews: "Последние отзывы",
  limit: "Лимит",
  limitsError: "Укажите лимиты",
  linkCopied: "Ссылка скопирована",
  loading: "Загрузка...",
  loadingAddresses: "Загрузка адресов...",
  localCurrency: "Местная валюта",
  mary: "Мары",
  maxLimit: "Макс. лимит",
  meetingCity: "Город встречи",
  merchantCenter: "P2P Центр",
  min: "мин.",
  minLimit: "Мин. лимит",
  minTrades: "Мин. сделок",
  minTradesRequired: "Минимум сделок: {min} (У вас: {current})",
  mpCompletion: "Выполнено",
  mpLimit: "Лимит",
  mpOnPlatform: "На платформе с",
  mpPositiveReviews: "положительных отзывов",
  mpSellerAds: "Объявления продавца",
  mpTrades: "Сделок",
  mpVolume: "Объём",
  myAds: "Мои объявления",
  myOrders: "Мои сделки",
  navAlys: "Обмен",
  navGapjyk: "Кошелек",
  navP2P: "P2P Маркет",
  networkError: "Ошибка сети",
  networkLabel: "Сеть",
  neutral: "Нормально",
  newAddressTitle: "Новый адрес",
  nickname: "Никнейм",
  noAds: "Нет активных объявлений для",
  noAdsDesc: "Попробуйте изменить сумму или валюту ({asset}/{fiat})",
  noComment: "Без комментария",
  noLabel: "Без названия",
  noOrders: "У вас еще нет сделок",
  notifications: "Уведомления",
  notificationsDisabled: "Уведомления отключены",
  notificationsEnabled: "Уведомления включены",
  onPayout: "На выплаты",
  onReceive: "На приём",
  online: "В сети",
  onlyWithKyc: "Только с KYC",
  openOrderBtn: "Открыть сделку",
  orderAttachCheck: "Прикрепите чек оплаты",
  orderAttachPhoto: "Пожалуйста, прикрепите фото или скриншот оплаты",
  orderCard: "💳 Банковская карта",
  orderCash: "🤝 Наличные",
  orderClickToChange: "Нажмите, чтобы изменить",
  orderCreated: "Сделка успешно создана!",
  orderCredited: "зачислено на кошелек",
  orderDebited: "списано с кошелька",
  orderDetailsInChat: "Реквизиты в чате",
  orderDisputeConfirm: "Вы уверены, что хотите вызвать апелляцию? Сделка будет заморожена до решения спора.",
  orderDisputeError: "Ошибка при отправке апелляции",
  orderDisputeSent: "Апелляция отправлена! Админ будет уведомлен.",
  orderExpiredMsg: "Сделка истекла. Оплата невозможна.",
  orderFrozen: "⚠️ Сделка заморожена. Ждите решения апелляции.",
  orderId: "Сделка",
  orderPaidMsg: "📢 Я оплатил заказ. Прикрепляю чек.",
  orderPaidSellerMessage: "{seller}, пожалуйста:\n1️⃣ Проверьте получение средств\n2️⃣ Подтвердите сделку в приложении",
  orderReviewError: "Ошибка при отправке отзыва",
  orderReviewPlaceholder: "Напишите пару слов о сделке (необязательно)...",
  orderSystemDisputeMsg: "🚨 Сделка приостановлена. Ожидайте решения администратора.",
  orderTmcell: "📱 Tmcell",
  orderUpdateError: "Ошибка при обновлении статуса",
  orderUploadCheck: "Загрузить чек",
  p2pCash: "Наличные",
  p2pLimit: "Лимит",
  p2pMerchant: "Мерчант",
  p2pMethod: "P2P Метод",
  p2pMinTrades: "Минимум сделок",
  p2pNoAds: "Нет активных объявлений для",
  p2pPayAmount: "Сумма к оплате",
  p2pReceiveAmount: "Вы получаете",
  p2pTradeConditions: "Условия сделки",
  p2pVerifyCode: "Требуется KYC (Верификация)",
  payAmount: "Сумма к оплате",
  paymentMethodError: "Выберите метод оплаты",
  paymentMethods: "Способы оплаты",
  paymentWindow: "Окно оплаты",
  perUnit: "за единицу",
  percentFromMarket: "Процент от рынка (%)",
  phone: "Телефон",
  positiveReviews: "положительных отзывов",
  price: "Цена",
  priceOrPercentError: "Укажите цену или процент",
  pricePerUnit: "Цена за 1 единицу",
  priceType: "Тип цены",
  private: "Приватное",
  proProgress: "Прогресс до Pro",
  proRequestError: "Ошибка при подаче заявки",
  proRequestSent: "Заявка отправлена поддержке",
  processing: "В обработке...",
  profileTitle: "Профиль",
  profileUSDTVolume: "USDT Объем",
  profileUpdated: "Профиль обновлён",
  protectionSettings: "Настройки защиты",
  public: "Публичное",
  publish: "Опубликовать",
  publishAd: "Опубликовать объявление",
  rating: "Рейтинг (%)",
  ratingText: "Рейтинг 4.8+",
  receiveAmount: "Вы получаете",
  redeemCode: "Активировать",
  refBonusDesc: "Бонус начисляется после того, как ваш друг совершит свою первую сделку.",
  refBonusPerFriend: "+15 USDT за каждого друга",
  refInviteFriends: "Пригласите друзей, чтобы начать зарабатывать вместе с RapTM",
  refRules: "Правила программы",
  refRulesDesc: "Приглашайте друзей и получайте бонус в USDT за каждую их сделку на платформе. Бонусы начисляются мгновенно.",
  refRulesTitle: "Правила программы",
  referralActive: "Активных",
  referralCopy: "Копировать",
  referralEarned: "Заработано",
  referralHistory: "История рефералов",
  referralLink: "Ваша ссылка",
  referralNoData: "У вас пока нет рефералов",
  referralRewardReceived: "🎁 Вы получили +15 USDT за активного реферала!",
  referralShare: "Пригласить",
  referralStats: "Статистика",
  referralStatusActive: "Активен",
  referralStatusPending: "Ожидание сделки",
  referralSubtitle: "Приглашайте друзей и зарабатывайте",
  referralTitle: "Реферальная программа",
  referralTotal: "Всего приглашено",
  refresh: "Обновить",
  requestError: "Ошибка запроса",
  returnToWallet: "Вернуться в кошелек",
  reviewSuccess: "Отзыв сохранен. Спасибо!",
  reviewTitle: "Оцените сделку",
  safeDeal: "Безопасная сделка",
  salmak: "Пополнить",
  save: "Сохранить",
  saveAddressBtn: "Сохранить адрес",
  searchPlaceholder: "Поиск по сумме...",
  sec2faDesc: "Защита Google Authenticator",
  sec2faDisable: "Отключение 2FA",
  sec2faDisableInput: "Введите код из приложения для отключения",
  sec2faDisableWarning: "Отключение 2FA снижает безопасность вашего аккаунта.",
  sec2faEnable: "Настройка 2FA",
  sec2faEnableScan: "Отсканируйте QR-код в приложении",
  sec2faEnableSuccess: "После включения 2FA будет запрашиваться при каждом выводе средств.",
  sec2faInput6Digit: "Введите 6-значный код",
  sec2faManual: "Или введите секретный ключ вручную:",
  sec2faNotSet: "Не настроено",
  sec2faSetupError: "Ошибка настройки 2FA",
  secChangePin: "Изменение PIN-кода",
  secConfirm: "Подтвердить",
  secConfirmPin: "Подтвердите PIN-код",
  secEmailAddress: "Email адрес",
  secEmailDesc: "На этот адрес будут приходить уведомления о важных событиях.",
  secEmailLinkDesc: "Привязать электронную почту",
  secEnter6Digit: "Введите 6-значный код",
  secFullProtection: "Ваш аккаунт максимально защищен",
  secInvalidCode: "Неверный код",
  secLinkEmail: "Привязка Email",
  secLinkPhone: "Привязка телефона",
  secLowProtection: "Повысьте безопасность аккаунта",
  secNewPin: "Новый PIN-код",
  secPhoneLinkDesc: "Привязать номер телефона",
  secPhoneNumber: "Номер телефона",
  secPhoneWarning: "Используйте номер, к которому у вас есть постоянный доступ.",
  secPinDesc: "Пин-код для операций",
  secProtectionLevel: "Уровень защиты",
  secSaveEmail: "Сохранить Email",
  secSaveError: "Ошибка сохранения",
  secSavePhone: "Сохранить номер",
  secSavePin: "Сохранить PIN",
  secWarning: "Никогда не передавайте ваш пароль, PIN-код или 2FA секрет третьим лицам. Сотрудники RapTM никогда не запрашивают эти данные.",
  security: "Безопасность",
  securityPin: "Безопасность и PIN",
  securityWarning: "Внимание! Не переводите крипту до получения наличных.",
  seeAllReviews: "Смотреть все",
  selectImage: "Пожалуйста, выберите изображение",
  sell: "Продать",
  sellBtn: "Продать",
  serverError: "Ошибка сервера",
  setAsDefault: "Использовать по умолчанию",
  shareProfile: "Поделиться профилем",
  stats: "Статистика",
  statusCancelled: "Отменена",
  statusCompleted: "Завершена",
  statusLabel: "Статус",
  statusPaid: "Оплачено",
  statusPending: "Ожидание оплаты",
  step1: "Напишите партнеру в чат для встречи.",
  step2: "После передачи денег нажмите кнопку 'Я оплатил'.",
  step3: "Партнер подтвердит получение и монеты зачислятся.",
  success: "Успешно!",
  time: "мин",
  tmcell: "Tmcell (Номер телефона)",
  totalCost: "Итоговая стоимость",
  tradeConditions: "Условия сделки",
  tradeConditionsPlaceholder: "Напишите детали (например: только на карту Халкбанк)",
  trades: "сделок",
  turkmenabat: "Туркменабад",
  typeLabel: "Тип",
  unverified: "Не верифицирован",
  updateError: "Ошибка при обновлении",
  userLabel: "Пользователь",
  verified: "Верифицирован",
  youGive: "Вы отдаете",
  youReceive: "Вы получаете",
  wal2faRequiredLevel: "Для вашего уровня доступа (Pro/Partner) обязательно наличие 2FA для вывода средств.",
  walActivationCode: "Код активации",
  walAddrError: "Ошибка получения адреса",
  walAmountRapCode: "Сумма ваучера",
  walAmountUsdt: "Сумма USDT",
  walAshgabat: "Ашхабад",
  walAvailableForExchange: "Доступно для обмена",
  walBalanceUpdated: "Баланс обновлён",
  walBalkanabat: "Балканабад",
  walBonusAccount: "Бонусный счет",
  walCash: "Наличные",
  walCashOperatorNote: "Наш оператор свяжется с вами в Telegram для подтверждения места встречи в городе {city}.",
  walCashWithdrawal: "Вывод наличных",
  walCashWithdrawalNote: "Оператор свяжется с вами для организации встречи.",
  walClaimError: "Ошибка получения USDT",
  walClaimSuccess: "🎉 1000 USDT зачислены на ваш счёт!",
  walCopied: "Скопировано",
  walCrypto: "Крипто",
  walDashoguz: "Дашогуз",
  walDeposit: "Пополнение",
  walDepositAddr: "Адрес пополнения",
  walDepositWithdraw: "Ввод и Вывод",
  walEnterAmount: "Введите сумму",
  walEnterNetworkAddr: "Введите {network} адрес",
  walEnterTxId: "Введите или вставьте TxID",
  walFilterAll: "ВСЕ",
  walFilterDeposit: "ПОПОЛНЕНИЯ",
  walFilterExchange: "ОБМЕН",
  walFilterWithdraw: "ВЫВОДЫ",
  walFullHistory: "Вся история",
  walGetTestUsdt: "Получить 1000 USDT",
  walGetTestTmt: "Получить 1000 TMT",
  walClaimTmtSuccess: "🎉 1000 TMT зачислены на ваш счёт!",
  walTmtDeposit: "Пополнение TMT",
  walTmtWithdraw: "Вывод TMT",
  walTmtPhone: "Номер телефона",
  walTmtPhonePlaceholder: "+993 6X XX-XX-XX",
  walTmtDepositNote: "Переведите TMT на номер администратора и введите номер отправителя.",
  walHistory: "История",
  walInDev: "Функция в разработке",
  walInsuffBalance: "Недостаточно баланса",
  walInvalidAddr: "Неверный адрес {network}",
  walInvalidFormat: "Неверный формат",
  walKycRequired: "Пожалуйста, пройдите верификацию (KYC) для вывода средств",
  walMary: "Мары",
  walMinDeposit: "Минимальный депозит {amount} USDT",
  walNetworkError: "Ошибка сети",
  walNetworkFeeLabel: "Комиссия сети:",
  walNoOps: "Нет операций",
  walRapCode: "RapCode",
  walRapCodeActivationNote: "Активация подарочных ваучеров и переводов внутри системы мгновенно и без комиссии.",
  walRecipientAddr: "Адрес получателя",
  walRequestCreated: "Заявка создана",
  walScanToPay: "Отсканируйте для оплаты",
  walSearchPlaceholder: "Поиск по сумме, дате или TxID...",
  walSeeAll: "Смотреть всё ({count})",
  walSelectCityWithdraw: "Выберите город для получения наличных",
  walSelectPaymentMethod: "Выберите способ оплаты",
  walStatusCancelled: "Отменено",
  walStatusCompleted: "Выполнено",
  walStatusFailed: "Ошибка",
  walStatusPending: "Ожидание",
  walStatusProcessing: "В обработке",
  walSubmitRequest: "ОТПРАВИТЬ ЗАЯВКУ",
  walToReceive: "К зачислению:",
  walTurkmenabat: "Туркменабад",
  walTxHash: "Hash транзакции (TxID)",
  walUserNotAuth: "Пользователь не авторизован",
  walValidFormat: "Верный формат",
  walVoucherCreation: "Создание ваучера",
  walVoucherCreationNote: "Ваучер можно передать другому пользователю для мгновенного зачисления.",
  walWithdrawAll: "ВЫВЕСТИ ВСЁ",
  walWithdrawAmount: "Сумма вывода",
  walWithdrawBtn: "Вывести средства",
  walWithdrawal: "Вывод средств",
  walWithdrawalNote: "Средства зачислятся в течение 15 минут",
  walYourCity: "Ваш город",
  walyutalar: "Валюты",
  whatToDo: "Что нужно сделать?"
};
