// src/lib/dicts/tm.ts
import { Dictionary } from './types';

export const tm: Dictionary = {
  accountDeleted: "Hasap ýatyryldy. Sag boluň!",
  adBuyerMustPassKYC: "Satyjy alyjy KYC geçmeli",
  adCash: "Nagt",
  adCashMethod: "{cash} / Usul",
  adCounterpartyProtection: "Garşydaşy goramak",
  adFinalPrice: "Jemi baha",
  adMinTrades: "Minimal üstünlikli söwdalar",
  adOnlyVerified: "Diňe tassyklananlar",
  adPaymentTime: "Töleg üçin wagt",
  adTerms: "Söwda şertleri (Düşündiriş)",
  adTrades: "söwda",
  addAddressBtn: "Salgy goşmak",
  addAddressDesc: "Çykaryşlary çaltlaşdyrmak üçin salgy goşuň",
  addressAdded: "Salgy goşuldy",
  addressBookTitle: "Salgylar kitaby",
  addressDeleted: "Salgy pozuldy",
  addressPlaceholder: "Gapjygyň salgysyny ýazyň",
  adminActiveDisputes: "Aktiw dawalar",
  adminActiveTrades: "Aktiw söwdalar",
  adminAllLevels: "Ähli derejeler",
  adminAllOps: "Hemmesi",
  adminAllStatus: "Ähli statuslar",
  adminAmount: "Möçber",
  adminApprove: "Tassyklamak",
  adminApproveBtn: "Tassyklamak",
  adminBack: "Yzyna",
  adminBlacklist: "Gara sanaw",
  adminBuyer: "Alyjy",
  adminCancelDeal: "Söwdany ýatyrmak",
  adminCashDesks: "Kassalar",
  adminChatHistory: "Çat taryhy",
  adminCodesActive: "Aktiw",
  adminCodesFees: "Komissiýalar (gazanylan)",
  adminCodesOps: "Kodlar",
  adminCodesTotal: "Jemi",
  adminCodesUsed: "Ulanylan",
  adminCodesVolume: "Göwrümi (ulanylan)",
  adminCompleteDeal: "Söwdany tamamlamak",
  adminConfirm: "Men gönderdim",
  adminCredited: "Admin tarapyndan goýuldy",
  adminCrypto: "Giriş/Çykyş",
  adminCryptoOps: "Kripto",
  adminDashboard: "Panel",
  adminDebited: "Admin tarapyndan aýryldy",
  adminDisputeArbitration: "Söwda appelýasiýasy #{id}",
  adminDisputeTitle: "Söwda appelýasiýasy #{id}",
  adminDisputeSubtitle: "DAWANY DOLANDYRYŞ",
  adminDisputeOpen: "Dawa açyk",
  adminDisputeView: "Çat taryhy we dawa çözmek",
  adminDisputes: "Dawalar",
  adminDocPhoto: "Resminama suraty",
  adminExchangeOps: "Çalyşmalar",
  adminExchanges: "Çalyşmalar",
  adminExchangesPending: "Garaşylýar",
  adminExchangesTotal: "Jemi",
  adminFeesToday: "Bugünki komissiýalar",
  adminFiat: "Fiat",
  adminForward: "Öňe",
  adminFreeze: "Doňdur",
  adminGlobalRate: "Global kurs",
  adminInQueue: "GARAŞYLYKDA",
  adminInvitePartner: "Partnýor çagyrmak",
  adminKYC: "KYC",
  adminKYCCheck: "KYC barlagy",
  adminKYCRequest: "Arza #{id}",
  adminKYCVerified: "KYC tassyklanan",
  adminLevels: "Derejeler",
  adminLoading: "Ýüklenilýär...",
  adminNoDisputes: "Aktiw dawa ýok",
  adminNoExchanges: "Çalyşma arzasy ýok",
  adminNoOps: "Amallar ýok",
  adminNoTransactions: "Tranzaksiýalar ýok",
  adminNoUsers: "Ulanyjylar ýok",
  adminOf: "den",
  adminOperations: "Amallar",
  adminPage: "Sah.",
  adminPanel: "Admin-Panel (Appelýasiýa)",
  adminPartnerDesc: "Bu salgy arkaly ulanyjy dessine Partner derejesini we 50 USDT bonus alar",
  adminPartnerLink: "Partnýor salgysy",
  adminPartners: "Partnýorlar",
  adminPaymentReceived: "Töleg gelip gowuşdy",
  adminPending: "Garaşylýar",
  adminPhotoNotUploaded: "Surat ýüklenmedi",
  adminRateFrozenWarn: "Kurs doňdurylan. Üýtgetmek mümkin däl.",
  adminReceiveAmount: "Alýar",
  adminReject: "Ret etmek",
  adminRejectBtn: "Ret etmek",
  adminReturn: "Yzyna gaýtarmak",
  adminReturnCryptoToSeller: "Kriptony satyja yzyna gaýtarýarys",
  adminSearch: "Gözle",
  adminSearchPlaceholder: "Gözleg (ulanyjy ady, ID)",
  adminSeller: "Satyjy",
  adminSendAmount: "Berýär",
  adminSendToAddress: "Salgy ugrat",
  adminSendToNumber: "Belgä ugrat",
  adminStats: "Statistika",
  adminSubtitle: "P2P Dolandyryş",
  adminTMTBalance: "TMT Balans",
  adminTitle: "Admin paneli",
  adminTotalUsers: "Ulanyjylar",
  adminTransferCryptoToBuyer: "Kriptony alyja geçirýäris",
  adminTxId: "TxID barlat",
  adminUSDTBalance: "USDT Balans",
  adminUser: "Ulanyjy",
  adminUserDetails: "Ulanyjy",
  adminUserInfo: "Ulanyjy barada maglumat",
  adminUserName: "Ady",
  adminUserNickname: "Lakam",
  adminUserRegDate: "Hasaba alnan senesi",
  adminUsers: "Ulanyjylar",
  adminVolume: "Söwda göwrümi",
  adminVolume24h: "24 sagat göwrümi",
  adminVolume7d: "7 gün göwrümi",
  adminWithdrawQueue: "Çykaryş garaşary",
  all: "Hemmesi",
  alyCaly: "Çalyşmak",
  amount: "Möçber",
  anonymous: "Anonim",
  apiDesc: "Biz söwdany awtomatlaşdyrmak we daşarky hyzmatlar bilen integrasiýa üçin güýçli API üstünde işleýäris.",
  apiManagement: "API Dolandyryş",
  apiTitle: "API Dolandyryş",
  ashgabat: "Aşgabat",
  asset: "Aktiw",
  autoReply: "Söwda şertleri (Awtosogap)",
  avatarUploadError: "Awatar ýüklemekde säwlik",
  bad: "Erbet",
  balanceLabel: "Umumy balans",
  balkanabat: "Balkanabat",
  becomePro: "Pro boluň",
  botAccountUnlinked: "🔗 Hasap aýryldy. Täzeden birikdirmek üçin /start ulanyň.",
  botAccountVerified: "Hasabyňyz üstünlikli tassyklanyldy 🎉",
  botAdDeactivated: "Siziň bildirişiňiz ýatyryldy.",
  botAdExpired: "⏰ <b>Bildirişiň möhleti geçdi</b>",
  botAdPublished: "📢 <b>Bildiriş çap edildi!</b>",
  botAdminWillReview: "Admin tiz wagtda dawany gözden geçirer.",
  botAmount: "Möçber",
  botBackToWallet: "👛 Gapjyga dolan",
  botBuyer: "👤 Alyjy",
  botCancelledByUser: "Ulanyjy tarapyndan ýatyryldy",
  botCheckTrades: "/status - Söwdalaryň ýagdaýyny barla",
  botConnectAccountTip: "🔗 Hasaby birikdirmek üçin programmada düwmäni ulanyň.",
  botCreateAd: "➕ Bildiriş döret",
  botCreateNewAd: "Islendik wagt täze bildiriş döredip bilersiňiz.",
  botCryptoAmount: "🪙 Kriptowalýuta",
  botDepositReceived: "Depozit goýuldy!",
  botDepositSuccess: "Serişdeler üstünlikli balansa goşuldy.",
  botDisableNotifications: "/disable - Bildirişleri öçür",
  botDisabled: "❌ Öçürilen",
  botDisputeOpened: "⚠️ {orderId} söwda boýunça dawa açyldy. Admini garaşyň.",
  botEnableNotifications: "/enable - Bildirişleri aç",
  botEnabled: "✅ Açyk",
  botEnglish: "🇬🇧 English",
  botExclusiveDeals: "✅ Eksklýuziw söwdalara gatnaşmak",
  botFrom: "👤 Kimden",
  botFromUser: "👤 Kimden",
  botGoToP2P: "📋 P2P geç",
  botHelpCommand: "/help - Kömek",
  botHelpCommands: "⚙️ <b>Buýruklar:</b>",
  botHelpDesc1: "🤖 Men söwda bildirişleri üçin P2P bot.",
  botHelpDesc2: "📱 <b>Nähili işleýär:</b>\n1. Hasaby programmada birikdiriň\n2. Söwda bildirişlerini alyň\n3. Sazlamalary dolandyryň",
  botHelpTitle: "❓ <b>Kömek</b>",
  botInitiator: "👤 Başlaýjy",
  botKYCApproved: "✅ <b>KYC tassyklanyldy!</b>",
  botKYCRejected: "❌ <b>KYC ret edildi</b>",
  botKeepItUp: "Şeýle dowam ediň! 🙌",
  botLanguageSelected: "✅ Dil saýlandy: ",
  botMessages: "🔔 Garşydaşlardan hatlar",
  botMyAds: "📋 Meniň bildirişlerim",
  botMyCommands: "📋 <b>Meniň buýruklarym:</b>",
  botMyOrders: "📋 Meniň söwdalarym",
  botMyProfile: "👤 Meniň profilim",
  botNetwork: "Tor",
  botNewMessage: "💬 <b>Täze hat</b>",
  botNewOrder: "🛒 <b>Täze söwda döredildi!</b>",
  botNewReview: "⭐ <b>Täze seslenme!</b>",
  botNoActiveDeals: "Sizde aktiw söwda ýok.",
  botNotificationsCommand: "/notifications - Bildirişleri dolandyr",
  botNotificationsDisabled: "❌ Bildirişler öçürildi!",
  botNotificationsEnabled: "✅ Bildirişler açyldy!",
  botNotificationsStatus: "🔔 <b>Bildirişler:</b> {status}\n\nAçmak ýa-da öçürmek üçin /enable ýa-da /disable ulanyň.",
  botNowAvailable: "Indi size elýeterli:",
  botNowYouWillReceive: "Indi siz alarsyňyz:",
  botOpenApp: "🚀 Programmany aç",
  botOpenChat: "💬 Çaty aç",
  botOpenOrder: "📋 Söwdany aç",
  botOpenProfile: "👤 Profili aç",
  botOrderAmount: "💰 Möçber",
  botOrderCancelled: "❌ <b>Söwda ýatyryldy</b>",
  botOrderCompleted: "🎉 <b>Söwda tamamlandy!</b>",
  botOrderNotifications: "🔔 Täze söwda bildirişleri",
  botOrderPaid: "✅ <b>Alyjy tölegi tassyklady!</b>",
  botP2PAssistant: "Men siziň şahsy P2P kömekçiňiz.",
  botPaymentConfirmed: "✅ {orderId} söwda boýunça töleg tassyklanyldy!",
  botPaymentStatus: "🔔 Töleg we tassyklama ýagdaýlary",
  botPaymentTime: "⏱ Töleg üçin wagt",
  botPendingPayment: "Tölege garaşylýar",
  botProfile: "Profil",
  botReason: "Sebäp",
  botReceived: "🪙 Alyndy",
  botRetryKYC: "📤 KYC gaýtala",
  botRussian: "🇷🇺 Русский",
  botSecurityUpdates: "🔔 Möhüm howpsuzlyk täzelemeleri",
  botSelectLanguage: "🌍 Dil saýlaň / Выберите язык / Select language",
  botSeller: "👤 Satyjy",
  botStatus: "Ýagdaýy",
  botThankForVerify: "Tassyklama üçin sag boluň!",
  botThankYou: "P2P Market ulananyňyz üçin sag boluň! 🙏",
  botThanksForConnect: "Bildirişlere birigeniňiz üçin sag boluň.",
  botTip: "💡 <b>Maslahat:</b> Möhüm wakalary sypdyrmazlyk üçin bildirişleri açyň!",
  botTrustedLevel: "✅ Ýokary ynam derejesi",
  botTryAgain: "Resminamalary täzeden ýükläp bilersiňiz.",
  botTurkmen: "🇹🇲 Türkmençe",
  botUnknownCommand: "❓ Näbelli buýruk. Sanaw üçin /help ulanyň.",
  botUnlimitedAds: "✅ Bildirişleri çäksiz döretmek",
  botUnlinkAccount: "/unlink - Hasaby aýyr",
  botWelcome: "👋 <b>P2P Market-e hoş geldiňiz!</b>",
  botWelcomeUser: "👋 <b>Hoш geldiňiz, {username}!</b>",
  botYourActiveDeals: "📊 <b>Siziň aktiw söwdalaryňyz:</b>\n\nAçmak üçin söwdanyň üstüne basyň:",
  botYourAd: "Bildirişiňiz indi marketde görünýär!",
  buy: "Satyn al",
  buyBtn: "Satyn al",
  cancel: "Ýatyr",
  cancelBtn: "ÝATYR",
  card: "Bank kartasy",
  cash: "Şäherde nagt",
  chatDispute: "Dawa / Appelýasiýa",
  chatNoMessages: "Çatda hat ýok",
  chatPlaceholder: "Hat ýazyň...",
  chatProblems: "Kynçylyklar ýüze çykdy?",
  chatRecently: "Ýaňyja onlaýndy",
  chatSelectImage: "Surat saýlaň",
  chatSendError: "Ugratmakda säwlik",
  city: "Şäher",
  codeActive: "Aktiw",
  codeCancelled: "Ýatyryldy",
  codeCommission: "Komissiýa",
  codeCopyInfo: "Kody göçüriň we alyja beriň",
  codeCreateBtn: "Kod döret",
  codeEmptyHistory: "Taryh boş",
  codeEmptyHistorySub: "Siz entek kod döretmediňiz ýa-da ulanmadyňyz",
  codeEnterPlaceholder: "TM-USDT-500-...",
  codeExpired: "Möhleti geçdi",
  codeExpires: "Möhleti",
  codeExpiresIn: "Möhleti: 24 sagat",
  codeFee: "Komissiýa",
  codeGenerated: "Kod döredildi!",
  codeIdKey: "ID Açary",
  codeLabel: "Promokod",
  codeOneTime: "Diňe bir gezek ulanyp bolýar",
  codeRedeemBtn: "Kody ulan",
  codeRedeemSuccess: "Pul hasaba goşuldy!",
  codeUsed: "Ulanyldy",
  codeValidUntil: "Möhleti",
  codeWarning1: "⚠️ Ulanmazdan ozal kody barlaň",
  codeWarning2: "⚠️ Kody diňe bir gezek ulanyp bolýar",
  codeWarning3: "⚠️ Öz döreden kodyňyzy ulanyp bilmersiňiz",
  codeYouCreated: "Siziň döredeniňiz",
  codeYouRedeemed: "Siziň ulananyňyz",
  codesHistory: "Taryh",
  codesSubtitle: "Nagt hasaplaşyklar",
  codesTitle: "Promokodlar",
  comingSoon: "Tiz wagtda",
  completion: "ýerine ýetirildi",
  confirm: "Tassyklamak",
  confirmCancel: "Söwdany ýatyrmak isleýändigiňize ynanýarsyňyzmy?",
  confirmDeleteAd: "Bildirişi pozmak isleýändigiňize ynanýarsyňyzmy?",
  confirmRec: "Alanyňy tassykhala",
  copied: "Göçürildi",
  createAd: "Bildiriş döret",
  createAdHeader: "Bildiriş döret",
  createAdWarning: "Ähli maglumatlary dykgat bilen barlaň. Bildirişi çap edeniňizden soň üýtgetmek mümkin.",
  createCode: "Kod döret",
  cryptocurrency: "Kriptowalýuta",
  currentLevel: "Häzirki derejäňiz",
  cykarmak: "Çykyş",
  dashoguz: "Daşoguz",
  daysText: "14 Gün",
  defaultLabel: "Bellenen",
  deleteAccount: "Hasaby poz",
  deleteAccountBtn: "HAWA, POZ",
  deleteAccountConfirmDesc: "Bu amal siziň profiliňizi ýapýar we ähli bildirişleri gizleýär. Tranzaksiýalaryňyz hasabatlylyk üçin bazada galar.",
  deleteAccountConfirmTitle: "Ynanýarsyňyzmy?",
  deleteAddressConfirm: "Bu salgyny pozmak isleýändigiňize ynanýarsyňyzmy?",
  digitalDollar: "Sanly dollar",
  edit: "Üýtget",
  email: "Poçta",
  emptyAddressBook: "Salgylar kitaby boş",
  enterAddress: "Salgy ýazyň",
  enterAmount: "Möçberi ýazyň",
  error: "Ýalňyşlyk ýüze çykdy",
  exAvailable: "Elýeterli",
  exBonusUsed: "Bonusdan aýryldy",
  exCancelled: "Ýatyryldy",
  exCommission: "Komissiýa",
  exConnectionError: "Aragatnaşyk ýalňyşlygy",
  exEnterPhone: "Telefon belgiňizi ýazyň",
  exFeeNote: "* Komissiýa ilki bonus hasabyndan, soňra esasy USDT balansyndan aýrylýar.",
  exFeePercent: "Komissiýa (%)",
  exHistory: "Çalyşma taryhy",
  exInstruction: "{amount} TMT-ny {phone} belgisine geçiriň we admin tassyklamasyna garaşyň.",
  exInsufficientBalanceFee: "Komissiýa üçin balans ýeterlik däl",
  exInsufficientUsdt: "Çalyşmak we komissiýa üçin USDT ýeterlik däl",
  exMainUsed: "Esasy balansdan aýryldy",
  exMinAmount: "Min. möçber",
  exNetworkFee: "Tor komissiýasy geçirilen möçberden aýrylar.",
  exPending: "Garaşylýar",
  exPhonePlaceholder: "+993 6X XX-XX-XX",
  exRate: "Kurs",
  exReverse: "Ugruny çalşyň",
  exSendTMT: "{amount} TMT geçiriň",
  exSendToAdmin: "TMT-ny adminiň belgisine geçiriň",
  exSettings: "Çalyşma sazlamalary",
  exSuccess: "Üstünlikli",
  exTMTName: "Türkmen manady",
  exTitle: "Çalyşmak",
  exUSDTName: "Tether USDT",
  exWhereToSend: "Manatlary nire ugratmaly?",
  exYouGive: "Siz berýärsiňiz",
  exYouPay: "Siz töleýärsiňiz",
  excellent: "Öräne gowy",
  exchangePrice: "Birža",
  exchangeStub: "Bu bölüm wagtlaýyn elýeterli däl.",
  faqAMLTitle: "AML Barlaglary",
  faqAPITitle: "API açarlary",
  faqArbitration: "Appelýasiýa näme?",
  faqArbitrationDesc: "Bu söwdada kynçylyk ýüze çykanda admin tarapyndan dawanyň çözülmegidir.",
  faqContactTelegram: "Telegram arkaly habarlaşmak",
  faqHowCreateAPI: "API açaryny nähili döretmeli?",
  faqHowCreateAPIDesc: "API bölümi işlenilýär we tiz wagtda elýeterli bolar.",
  faqHowDepositCash: "Nagt nähili goýmaly?",
  faqHowDepositCashDesc: "Gapjyk -> Goýmak -> Nagt giriň we şäheriňizi saýlaň.",
  faqHowDepositCrypto: "Kripto nähili goýmaly?",
  faqHowDepositCryptoDesc: "Gapjyk -> Goýmak -> Kripto giriň we gözükdirijini yzarlaň.",
  faqHowInvite: "Dosty nähili çagyrmaly?",
  faqHowInviteDesc: "Profil -> Referal programmada salgyňyzy göçüriň.",
  faqHowLevelUp: "Derejäni nähili ýokarlandyrmaly?",
  faqHowLevelUpDesc: "Söwda göwrümini artdyryň we tassyklamadan geçiň.",
  faqHowWithdrawTime: "Çykaryş wagty?",
  faqHowWithdrawTimeDesc: "Kripto gapjyklara çykaryş 15 minuda çenli, nagt bolsa operator bilen ylalaşykly.",
  faqLegalDocs: "Hukuk resminamalary",
  faqLevelsTitle: "Maliýe derejeleri",
  faqNetSupport: "Haýsy torlar goldanylýar?",
  faqNetSupportDesc: "Biz TRC-20, ERC-20, BEP-20 we Aptos torlarynda USDT goldaýarys.",
  faqNoResults: "Hiç zat tapylmady",
  faqOfficesTitle: "Ofisler",
  faqP2PDetails: "P2P nähili işleýär?",
  faqP2PDetailsDesc: "Siz bildiriş saýlaýarsyňyz, dostuňyza pul geçirýärsiňiz we platforma kripto almagyňyza kepil geçýär.",
  faqP2PTimeout: "Hyzmatdaş tölemese näme bolar?",
  faqP2PTimeoutDesc: "Söwda wagt geçenden soň awtomatiki ýatyrylar.",
  faqQuestionsLeft: "Soraglar galdymy?",
  faqReferralTitle: "Referal programma",
  faqRewards: "Nähili baýraklar?",
  faqRewardsDesc: "Ilkinji söwdasyny eden her bir dostuňyz üçin 15 USDT alarsyňyz.",
  faqRiskScore: "Risk Score näme?",
  faqRiskScoreDesc: "Bu gapjygyňyzyň töwekgelçilik görkezijisidir. Ýokary töwekgelçilik hasabyňyzyň ýapylmagyna sebäp bolup biler.",
  faqSearchPlaceholder: "Soraglardan gözle...",
  faqSectionAML: "AML Barlaglary",
  faqSectionAPI: "API açarlary",
  faqSectionAccount: "Hasap we howpsuzlyk",
  faqSectionFinance: "Goýmak we çykarmak",
  faqSectionLevels: "Maliýe derejeleri",
  faqSectionOffices: "Ofisler",
  faqSectionP2P: "P2P platformasy",
  faqSectionReferral: "Referal programma",
  faqSubtitle: "FAQ we resminamalar",
  faqSupportNote: "Biziň kömek gullugymyzyň hünärmenleri 24/7 işleýär we size islendik wagt kömek etmäge taýýar.",
  faqTitle: "Kömek merkezi",
  faqTryChangingQuery: "Gözlegiňizi üýtgedip görüň",
  faqWhatIsAML: "AML näme?",
  faqWhatIsAMLDesc: "Tranzaksiýalaryňyzyň arassalygyny barlaýan pul ýuwulmagyna garşy sistema.",
  faqWhereOffices: "Ofisler nirede?",
  faqWhereOfficesDesc: "Biziň ofislerimiz Türkmenistanyň ähli welaýatlarynda ýerleşýär.",
  faqWithdrawTime: "Pul näçe wagtdan gelýär?",
  faqWithdrawTimeDesc: "Adatça çykaryş 5-den 15 minuda çenli wagt alýar.",
  fastConfirm: "Çalt tassyklama",
  fiat: "Fiat",
  fiatCurrency: "Fiat walýuta",
  filterAmount: "Möçber",
  fixed: "Bellenen",
  floating: "Üýtgäp duran",
  goBack: "Yzyna dolan",
  help: "Kömek",
  helpSubtitle: "Maglumat we goldaw",
  iPay: "Men töledim",
  insufficientUsdtSeller: "Satyjynyň balansynda USDT ýeterlik däl",
  insufficientTmtSeller: "Satyjynyň balansynda TMT ýeterlik däl",
  kycApproved: "Hasap tassyklanyldy",
  kycApprovedDesc: "Size ähli çäklendirmeler we tassyklanan söwdagärler bilen söwda etmek elýeterlidir.",
  kycLabel: "Tassyklama",
  kycMaxFileSize: "Faýlyň ölçegi 5MB-den kiçi bolmaly",
  kycNextStepDone: "Tassyklanandan soň tassyklama belgisi berler",
  kycNextSteps: "Indi näme?",
  kycOnCheck: "Barlagda",
  kycOnlyJpegPng: "Diňe JPEG we PNG suratlary",
  kycOpenCam: "Kamerany / Galereýany aç",
  kycOpenCamera: "Kamerany / Galereýany aç",
  kycOr: "ýa-da",
  kycPass: "Geç",
  kycPending: "Barlagda",
  kycPendingDesc: "Admin resminamalaryňyzy barlaýar. Adatça bu 10-15 minut alýar.",
  kycPendingDesc2: "Admin resminamalaryňyzy barlaýar. Adatça bu 10-15 minut alýar.",
  kycPendingTitle: "Arza barlagda",
  kycPendingTitle2: "Arza barlagda",
  kycPhotoRequired: "Ilki iki suraty-da ýükläň",
  kycPossibleReasons: "Mümkin bolan sebäpler:",
  kycPossibleReasons2: "Mümkin bolan sebäpler:",
  kycReason1: "Surat düşnükli däl ýa-da maglumatlar görünmeýär",
  kycReason2: "Resminamanyň möhleti geçen",
  kycReason3: "Surat profiliňize laýyk gelmeýär",
  kycReasonBlurry: "Surat düşnükli däl ýa-da maglumatlar görünmeýär",
  kycReasonExpired: "Resminamanyň möhleti geçen",
  kycReasonMismatch: "Surat profiliňize laýyk gelmeýär",
  kycRejected: "Ret edildi",
  kycRejectedDesc: "Admin maglumatlary tassyklap bilmedi.",
  kycRejectedDesc2: "Admin maglumatlary tassyklap bilmedi.",
  kycRejectedTitle: "Arza ret edildi",
  kycRejectedTitle2: "Arza ret edildi",
  kycRequired: "KYC tassyklamasy gerek",
  kycSecurity: "Platforma howpsuzlygy",
  kycSelectFile: "Faýl saýlaň",
  kycStep1: "1-nji ädim: Resminama suratyny ýükläň",
  kycStep1Title: "1-nji ädim: Pasport bilen selfi",
  kycStep1Wait: "15 minudyň dowamynda barlaga garaşyň.",
  kycStep2: "2-nji ädim: Pasport skany",
  kycStep2Check: "Ýagdaýyny Profil bölüminden barlaň.",
  kycStep2Title: "2-nji ädim: Pasport skany",
  kycStep3Title: "3-nji ädim: Barlaga ugradyň",
  kycSelfieWithPassport: "Pasport bilen selfi",
  kycPassportScan: "Pasport skany",
  kycStep3Trade: "Tassyklanandan soň ähli funksiýalar elýeterli bolar.",
  kycSubmitBtn: "Barlaga ugrat",
  kycSubmitError: "Arza ugratmakda säwlik",
  kycSubmitSuccess: "Arza ugradyldy! Admin tarapyndan barlanylmagyna garaşyň.",
  kycSubmitting: "Ugradylýar...",
  kycTitle: "Tassyklama (KYC)",
  kycVerifiedDesc: "Size ähli çäklendirmeler we tassyklanan söwdagärler bilen söwda etmek elýeterlidir.",
  kycVerifiedTitle: "Hasap tassyklanyldy",
  kycWhatNext: "Indi näme?",
  kycWhy: "KYC näme üçin gerek?",
  kycWhyDesc: "KYC platformany galplykdan goramaga kömek edýär we serişdeleriňiziň howpsuzlygyny üpjün edýär.",
  kycWhyDesc2: "KYC platformany galplykdan goramaga kömek edýär we serişdeleriňiziň howpsuzlygyny üpjün edýär.",
  kycWhyTitle: "KYC näme üçin gerek?",
  labelPlaceholder: "Meselem: Meniň Ledger-im",
  labelTitle: "Ady (hökman däl)",
  lastReviews: "Soňky seslenmeler",
  limit: "Çäk",
  limitsError: "Çäklendirmeleri görkeziň",
  linkCopied: "Salgy göçürildi",
  loading: "Ýüklenýär...",
  loadingAddresses: "Salgylar ýüklenýär...",
  localCurrency: "Ýerli walýuta",
  mary: "Mary",
  maxLimit: "Maks. çäk",
  meetingCity: "Duşuşyk şäheri",
  merchantCenter: "P2P merkezi",
  min: "min.",
  minLimit: "Min. çäk",
  minTrades: "Min. söwda",
  minTradesRequired: "Minimal söwda: {min} (Sizde: {current})",
  mpCompletion: "Ýerine ýetirildi",
  mpLimit: "Çäk",
  mpOnPlatform: "Platformada şundan bäri",
  mpPositiveReviews: "oňyn seslenmeler",
  mpSellerAds: "Satyjynyň bildirişleri",
  mpTrades: "Söwdalar",
  mpVolume: "Göwrüm",
  myAds: "Bildirişlerim",
  myOrders: "Söwdalarym",
  navAlys: "Çalyşmak",
  navGapjyk: "Gapjyk",
  navP2P: "P2P market",
  networkError: "Tor ýalňyşlygy",
  networkLabel: "Tor",
  neutral: "Kadaly",
  newAddressTitle: "Täze salgy",
  nickname: "Lakam",
  noAds: "Bildiriş tapylmady:",
  noAdsDesc: "Möçberi ýa-da walýutany üýtgetmäge synanyşyň ({asset}/{fiat})",
  noComment: "Seslenmesiz",
  noLabel: "Adsyz",
  noOrders: "Sizde entek söwda ýok",
  notifications: "Bildirişler",
  notificationsDisabled: "Bildirişler öçürildi",
  notificationsEnabled: "Bildirişler açyldy",
  onPayout: "Çykaryş üçin",
  onReceive: "Almak üçin",
  online: "Onlaýn",
  onlyWithKyc: "Diňe KYC bilen",
  openOrderBtn: "Söwdany aç",
  orderAttachCheck: "Töleg çekini goşuň",
  orderAttachPhoto: "Surat ýa-da skrinşot goşuň",
  orderCard: "💳 Bank kartasy",
  orderCash: "🤝 Nagt",
  orderClickToChange: "Üýtgetmek üçin basyň",
  orderCreated: "Söwda üstünlikli döredildi!",
  orderCredited: "gapjyga goşuldy",
  orderDebited: "gapjykdan aýryldy",
  orderDetailsInChat: "Maglumatlar çatda",
  orderDisputeConfirm: "Appelýasiýa çagyrmak isleýärsiňizmi? Söwda çözülýänçä doňdurylar.",
  orderDisputeError: "Arza ugratmakda säwlik",
  orderDisputeSent: "Arza ugradyldy! Admin habardar ediler.",
  orderExpiredMsg: "Söwda möhleti geçdi. Töleg mümkin däl.",
  orderFrozen: "⚠️ Söwda doňduryldy. Appelýasiýa kararyna garaşyň.",
  orderId: "Söwda",
  orderPaidMsg: "📢 Men töledim. Çeki goşýaryn.",
  orderPaidSellerMessage: "{seller}, haýyş:\n1️⃣ Puluň gelendigini barlaň\n2️⃣ Programmada söwdany tassyklaň",
  orderReviewError: "Seslenme ugratmakda säwlik",
  orderReviewPlaceholder: "Söwda barada birnäçe söz ýazyň (hökman däl)...",
  orderSystemDisputeMsg: "🚨 Söwda saklandy. Admin kararyna garaşyň.",
  orderTmcell: "📱 Tmcell",
  orderUpdateError: "Ýagdaýy üýtgetmekde säwlik",
  orderUploadCheck: "Çeki ýükle",
  p2pCash: "Nagt",
  p2pLimit: "Çäk",
  p2pMerchant: "Söwdagär",
  p2pMethod: "P2P usuly",
  p2pMinTrades: "Minimal söwda",
  p2pNoAds: "Bildiriş tapylmady:",
  p2pPayAmount: "Töleg möçberi",
  p2pReceiveAmount: "Siz alýarsyňyz",
  p2pTradeConditions: "Söwda şertleri",
  p2pVerifyCode: "KYC tassyklamasy gerek",
  payAmount: "Töleg möçberi",
  paymentMethodError: "Töleg usulyny saýlaň",
  paymentMethods: "Töleg usullary",
  paymentWindow: "Töleg wagty",
  perUnit: "birlik üçin",
  percentFromMarket: "Marketden göterim (%)",
  phone: "Telefon",
  positiveReviews: "oňyn seslenmeler",
  price: "Baha",
  priceOrPercentError: "Bahany ýa-da göterimi görkeziň",
  pricePerUnit: "1 birlik üçin baha",
  priceType: "Bahanyň görnüşi",
  private: "Şahsy",
  proProgress: "Pro-a çenli ösüş",
  proRequestError: "Arza bermekde säwlik",
  proRequestSent: "Arza kömek gullugyna ugradyldy",
  processing: "Işlenilýär...",
  profileTitle: "Profil",
  profileUSDTVolume: "USDT göwrümi",
  profileUpdated: "Profil täzelendi",
  protectionSettings: "Gorag sazlamalary",
  public: "Açyk",
  publish: "Çap et",
  publishAd: "Bildirişi çap et",
  rating: "Reýting (%)",
  ratingText: "Reýting 4.8+",
  receiveAmount: "Siz alýarsyňyz",
  redeemCode: "Ulanmak",
  refBonusDesc: "Bonus dostuňyz ilkinji söwdasyny edenden soň berilýär.",
  refBonusPerFriend: "Her dost üçin +15 USDT",
  refInviteFriends: "Dostlaryňyzy RapTM bilen gazanmaga çagyryň",
  refRules: "Programma düzgünleri",
  refRulesDesc: "Dostlaryňyzy çagyryň we olaryň her söwdasy üçin USDT bonus alyň. Bonuslar dessine hasaba goşulýar.",
  refRulesTitle: "Programma düzgünleri",
  referralActive: "Aktiwler",
  referralCopy: "Göçür",
  referralEarned: "Gazanyldy",
  referralHistory: "Referal taryhy",
  referralLink: "Siziň salgyňyz",
  referralNoData: "Sizde entek referal ýok",
  referralRewardReceived: "🎁 Aktiw referal üçin +15 USDT aldyňyz!",
  referralShare: "Çagyrmak",
  referralStats: "Statistika",
  referralStatusActive: "Aktiw",
  referralStatusPending: "Söwdada garaşylýar",
  referralSubtitle: "Dostlaryňyzy çagyryň we gazanyň",
  referralTitle: "Referal programma",
  referralTotal: "Jemi çagyrylanlar",
  refresh: "Täzele",
  requestError: "Soraşyň ýalňyşlygy",
  returnToWallet: "Gapjyga dolan",
  reviewSuccess: "Seslenme ýatda saklandy. Sag boluň!",
  reviewTitle: "Söwdany bahalandyryň",
  safeDeal: "Howpsuz söwda",
  salmak: "Goýmak",
  save: "Ýatda sakla",
  saveAddressBtn: "Salgyny ýatda sakla",
  searchPlaceholder: "Möçber boýunça gözleg...",
  sec2faDesc: "Google Authenticator goragy",
  sec2faDisable: "2FA öçürmek",
  sec2faDisableInput: "Öçürmek üçin programmada kody ýazyň",
  sec2faDisableWarning: "2FA öçürmek hasabyňyzyň howpsuzlygyny peseldýär.",
  sec2faEnable: "2FA sazlamak",
  sec2faEnableScan: "Programmada QR-kody skanirläň",
  sec2faEnableSuccess: "2FA açylandan soň, pul çykarmak üçin her gezek soralar.",
  sec2faInput6Digit: "6 belgili kody ýazyň",
  sec2faManual: "Ýa-da açary el bilen ýazyň:",
  sec2faNotSet: "Sazlanmadyk",
  sec2faSetupError: "2FA sazlamakda säwlik",
  secChangePin: "PIN-kody üýtgetmek",
  secConfirm: "Tassyklamak",
  secConfirmPin: "PIN-kody tassyklaň",
  secEmailAddress: "Email salgysy",
  secEmailDesc: "Bu salga möhüm wakalar barada bildirişler geler.",
  secEmailLinkDesc: "Elektron poçtany birikdiriň",
  secEnter6Digit: "6 belgili kody ýazyň",
  secFullProtection: "Hasabyňyz doly goragly",
  secInvalidCode: "Nädogry kod",
  secLinkEmail: "Email birikdirmek",
  secLinkPhone: "Telefon birikdirmek",
  secLowProtection: "Howpsuzlygy artdyryň",
  secNewPin: "Täze PIN-kod",
  secPhoneLinkDesc: "Telefon belgisini birikdiriň",
  secPhoneNumber: "Telefon belgisi",
  secPhoneWarning: "Hemişe elýeterli bolan belgiňizi ulanyň.",
  secPinDesc: "Amallar üçin PIN-kod",
  secProtectionLevel: "Gorag derejesi",
  secSaveEmail: "Email ýatda sakla",
  secSaveError: "Ýazgyda säwlik",
  secSavePhone: "Belgini ýatda sakla",
  secSavePin: "PIN-i ýatda sakla",
  secWarning: "Parolyňyzy, PIN-koduňyzy ýa-da 2FA açaryňyzy hiç kime bermäň. RapTM işgärleri bu maglumatlary hiç wagt soramaýarlar.",
  security: "Howpsuzlyk",
  securityPin: "Howpsuzlyk we PIN",
  securityWarning: "Üns beriň! Nagt pul almazdan ozal kripto ugratmaň.",
  seeAllReviews: "Ählisini gör",
  selectImage: "Surat saýlaň",
  sell: "Satmak",
  sellBtn: "Satmak",
  serverError: "Serwer ýalňyşlygy",
  setAsDefault: "Esasy hökmünde ulan",
  shareProfile: "Profili paýlaş",
  stats: "Statistika",
  statusCancelled: "Ýatyryldy",
  statusCompleted: "Tamamlandy",
  statusLabel: "Ýagdaýy",
  statusPaid: "Tölendi",
  statusPending: "Tölege garaşylýar",
  step1: "Duşuşyk üçin çatda hyzmatdaşyňyza ýazyň.",
  step2: "Puly bereniňizden soň 'Men töledim' düwmäni basyň.",
  step3: "Hyzmatdaş alandygyny tassyklar we pulyňyz gelip gowşar.",
  success: "Üstünlikli!",
  time: "min",
  tmcell: "Tmcell (Telefon belgisi)",
  totalCost: "Jemi baha",
  tradeConditions: "Söwda şertleri",
  tradeConditionsPlaceholder: "Jikme-jiklikleri ýazyň (meselem: diňe Halkbank kartyna)",
  trades: "söwda",
  turkmenabat: "Türkmenabat",
  typeLabel: "Görnüşi",
  unverified: "Tassyklanmadyk",
  updateError: "Täзеlemekde säwlik",
  userLabel: "Ulanyjy",
  verified: "Tassyklanan",
  youGive: "Siz berýärsiňiz",
  youReceive: "Siz alýarsyňyz",
  wal2faRequiredLevel: "Siziň derejäňiz (Pro/Partner) üçin pul çykarmakda 2FA hökmanydyr.",
  walActivationCode: "Aktiwasiýa kody",
  walAddrError: "Salgy almakda säwlik",
  walAmountRapCode: "Wauçer möçberi",
  walAmountUsdt: "USDT möçberi",
  walAshgabat: "Aşgabat",
  walAvailableForExchange: "Çalyşmak üçin elýeterli",
  walBalanceUpdated: "Balans täzelendi",
  walBalkanabat: "Balkanabat",
  walBonusAccount: "Bonus hasaby",
  walCash: "Nagt",
  walCashOperatorNote: "Biziň operatorymyz {city} şäherinde duşuşyk ýerini tassyklamak üçin Telegram arkaly habarlaşar.",
  walCashWithdrawal: "Nagt pul çykarmak",
  walCashWithdrawalNote: "Operator duşuşygy gurnamak üçin habarlaşar.",
  walClaimError: "USDT almakda säwlik",
  walClaimSuccess: "🎉 1000 USDT hasabyňyza goşuldy!",
  walCopied: "Göçürildi",
  walCrypto: "Kripto",
  walDashoguz: "Daşoguz",
  walDeposit: "Goýmak",
  walDepositAddr: "Goýum salgysy",
  walDepositWithdraw: "Giriş we Çykyş",
  walEnterAmount: "Möçberi ýazyň",
  walEnterNetworkAddr: "{network} salgysyny ýazyň",
  walEnterTxId: "TxID ýazyň ýa-da goýuň",
  walFilterAll: "ÄHLISI",
  walFilterDeposit: "GOÝUMLAR",
  walFilterExchange: "ÇALYŞMAK",
  walFilterWithdraw: "ÇYKARMALAR",
  walFullHistory: "Ähli taryh",
  walGetTestUsdt: "1000 USDT al",
  walGetTestTmt: "1000 TMT al",
  walClaimTmtSuccess: "🎉 1000 TMT hasabyňyza goşuldy!",
  walTmtDeposit: "TMT goýmak",
  walTmtWithdraw: "TMT çykarmak",
  walTmtPhone: "Telefon belgisi",
  walTmtPhonePlaceholder: "+993 6X XX-XX-XX",
  walTmtDepositNote: "TMT-ny adminiň telefon belgisini iberiň we iberijiniň belgisini ýazyň.",
  walHistory: "Taryh",
  walInDev: "Funksiýa işlenilýär",
  walInsuffBalance: "Balans ýeterlik däl",
  walInvalidAddr: "Nädogry {network} salgysy",
  walInvalidFormat: "Nädogry format",
  walKycRequired: "Pul çykarmak üçin KYC tassyklamasyny geçiň",
  walMary: "Mary",
  walMinDeposit: "Minimal depozit {amount} USDT",
  walNetworkError: "Tor ýalňyşlygy",
  walNetworkFeeLabel: "Tor komissiýasy:",
  walNoOps: "Amallar ýok",
  walRapCode: "RapCode",
  walRapCodeActivationNote: "Sowgat wauçerlerini we sistema içindäki geçirmeleri dessine we komissiýasyz aktiwleşdiriň.",
  walRecipientAddr: "Alyjynyň salgysy",
  walRequestCreated: "Arza döredildi",
  walScanToPay: "Tölemek üçin skanirläň",
  walSearchPlaceholder: "Möçber, sene ýa-da TxID boýunça gözleg...",
  walSeeAll: "Ählisini gör ({count})",
  walSelectCityWithdraw: "Nagt pul almak üçin şäheri saýlaň",
  walSelectPaymentMethod: "Töleg usulyny saýlaň",
  walStatusCancelled: "Ýatyryldy",
  walStatusCompleted: "Ýerine ýetirildi",
  walStatusFailed: "Ýalňyşlyk",
  walStatusPending: "Garaşylýar",
  walStatusProcessing: "Işlenilýär",
  walSubmitRequest: "ARZANY UGRAT",
  walToReceive: "Gowşurmaly:",
  walTurkmenabat: "Türkmenabat",
  walTxHash: "Tranzaksiýa haşy (TxID)",
  walUserNotAuth: "Ulanyjy awtorizasiýa geçmedik",
  walValidFormat: "Dogry format",
  walVoucherCreation: "Wauçer döretmek",
  walVoucherCreationNote: "Wauçeri başga ulanyja dessine hasaba goşmak üçin berip bilersiňiz.",
  walWithdrawAll: "ÄHLISINI ÇYKAR",
  walWithdrawAmount: "Çykaryş möçberi",
  walWithdrawBtn: "Puly çykar",
  walWithdrawal: "Pul çykarmak",
  walWithdrawalNote: "Serişdeler 15 minudyň dowamynda hasaba goşular",
  walYourCity: "Siziň şäheriňiz",
  walyutalar: "Walýutalar",
  whatToDo: "Näme etmeli?"
};
